// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

package types

import (
	"errors"
	"fmt"
)

type AGUIEvent struct {
	ObjectReference

	EventType string `json:"event_type"`
	Payload   string `json:"payload,omitempty"`
	Seq       int    `json:"seq,omitempty"`
	SessionID string `json:"session_id"`
}

type AGUIEventList struct {
	ListMeta
	Items []AGUIEvent `json:"items"`
}

func (l *AGUIEventList) GetItems() []AGUIEvent { return l.Items }
func (l *AGUIEventList) GetTotal() int         { return l.Total }
func (l *AGUIEventList) GetPage() int          { return l.Page }
func (l *AGUIEventList) GetSize() int          { return l.Size }

type AGUIEventBuilder struct {
	resource AGUIEvent
	errors   []error
}

func NewAGUIEventBuilder() *AGUIEventBuilder {
	return &AGUIEventBuilder{}
}

func (b *AGUIEventBuilder) EventType(v string) *AGUIEventBuilder {
	b.resource.EventType = v
	return b
}

func (b *AGUIEventBuilder) Payload(v string) *AGUIEventBuilder {
	b.resource.Payload = v
	return b
}

func (b *AGUIEventBuilder) Seq(v int) *AGUIEventBuilder {
	b.resource.Seq = v
	return b
}

func (b *AGUIEventBuilder) SessionID(v string) *AGUIEventBuilder {
	b.resource.SessionID = v
	return b
}

func (b *AGUIEventBuilder) Build() (*AGUIEvent, error) {
	if b.resource.EventType == "" {
		b.errors = append(b.errors, fmt.Errorf("event_type is required"))
	}
	if b.resource.SessionID == "" {
		b.errors = append(b.errors, fmt.Errorf("session_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type AGUIEventPatchBuilder struct {
	patch map[string]any
}

func NewAGUIEventPatchBuilder() *AGUIEventPatchBuilder {
	return &AGUIEventPatchBuilder{patch: make(map[string]any)}
}

func (b *AGUIEventPatchBuilder) EventType(v string) *AGUIEventPatchBuilder {
	b.patch["event_type"] = v
	return b
}

func (b *AGUIEventPatchBuilder) Payload(v string) *AGUIEventPatchBuilder {
	b.patch["payload"] = v
	return b
}

func (b *AGUIEventPatchBuilder) Seq(v int) *AGUIEventPatchBuilder {
	b.patch["seq"] = v
	return b
}

func (b *AGUIEventPatchBuilder) SessionID(v string) *AGUIEventPatchBuilder {
	b.patch["session_id"] = v
	return b
}

func (b *AGUIEventPatchBuilder) Build() map[string]any {
	return b.patch
}
