// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z

package types

import (
	"errors"
	"fmt"
)

type Agent struct {
	ObjectReference

	Name        string `json:"name"`
	OwnerUserID string `json:"owner_user_id"`
	Prompt      string `json:"prompt,omitempty"`
	Version     int    `json:"version,omitempty"`
}

type AgentList struct {
	ListMeta
	Items []Agent `json:"items"`
}

func (l *AgentList) GetItems() []Agent { return l.Items }
func (l *AgentList) GetTotal() int     { return l.Total }
func (l *AgentList) GetPage() int      { return l.Page }
func (l *AgentList) GetSize() int      { return l.Size }

type AgentBuilder struct {
	resource Agent
	errors   []error
}

func NewAgentBuilder() *AgentBuilder {
	return &AgentBuilder{}
}

func (b *AgentBuilder) Name(v string) *AgentBuilder {
	b.resource.Name = v
	return b
}

func (b *AgentBuilder) OwnerUserID(v string) *AgentBuilder {
	b.resource.OwnerUserID = v
	return b
}

func (b *AgentBuilder) Prompt(v string) *AgentBuilder {
	b.resource.Prompt = v
	return b
}

func (b *AgentBuilder) Build() (*Agent, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.OwnerUserID == "" {
		b.errors = append(b.errors, fmt.Errorf("owner_user_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type AgentPatchBuilder struct {
	patch map[string]any
}

func NewAgentPatchBuilder() *AgentPatchBuilder {
	return &AgentPatchBuilder{patch: make(map[string]any)}
}

func (b *AgentPatchBuilder) Prompt(v string) *AgentPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *AgentPatchBuilder) Build() map[string]any {
	return b.patch
}
