// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package types

import (
	"errors"
	"fmt"
)

type AgentMessage struct {
	ObjectReference

	Body string `json:"body,omitempty"`
	Read bool `json:"read,omitempty"`
	RecipientAgentID string `json:"recipient_agent_id"`
	SenderAgentID string `json:"sender_agent_id,omitempty"`
	SenderName string `json:"sender_name,omitempty"`
	SenderUserID string `json:"sender_user_id,omitempty"`
}

type AgentMessageList struct {
	ListMeta
	Items []AgentMessage `json:"items"`
}

func (l *AgentMessageList) GetItems() []AgentMessage { return l.Items }
func (l *AgentMessageList) GetTotal() int                  { return l.Total }
func (l *AgentMessageList) GetPage() int                   { return l.Page }
func (l *AgentMessageList) GetSize() int                   { return l.Size }

type AgentMessageBuilder struct {
	resource AgentMessage
	errors   []error
}

func NewAgentMessageBuilder() *AgentMessageBuilder {
	return &AgentMessageBuilder{}
}


func (b *AgentMessageBuilder) Body(v string) *AgentMessageBuilder {
	b.resource.Body = v
	return b
}

func (b *AgentMessageBuilder) Read(v bool) *AgentMessageBuilder {
	b.resource.Read = v
	return b
}

func (b *AgentMessageBuilder) RecipientAgentID(v string) *AgentMessageBuilder {
	b.resource.RecipientAgentID = v
	return b
}

func (b *AgentMessageBuilder) SenderAgentID(v string) *AgentMessageBuilder {
	b.resource.SenderAgentID = v
	return b
}

func (b *AgentMessageBuilder) SenderName(v string) *AgentMessageBuilder {
	b.resource.SenderName = v
	return b
}

func (b *AgentMessageBuilder) SenderUserID(v string) *AgentMessageBuilder {
	b.resource.SenderUserID = v
	return b
}


func (b *AgentMessageBuilder) Build() (*AgentMessage, error) {
	if b.resource.RecipientAgentID == "" {
		b.errors = append(b.errors, fmt.Errorf("recipient_agent_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type AgentMessagePatchBuilder struct {
	patch map[string]any
}

func NewAgentMessagePatchBuilder() *AgentMessagePatchBuilder {
	return &AgentMessagePatchBuilder{patch: make(map[string]any)}
}


func (b *AgentMessagePatchBuilder) Body(v string) *AgentMessagePatchBuilder {
	b.patch["body"] = v
	return b
}

func (b *AgentMessagePatchBuilder) Read(v bool) *AgentMessagePatchBuilder {
	b.patch["read"] = v
	return b
}

func (b *AgentMessagePatchBuilder) RecipientAgentID(v string) *AgentMessagePatchBuilder {
	b.patch["recipient_agent_id"] = v
	return b
}

func (b *AgentMessagePatchBuilder) SenderAgentID(v string) *AgentMessagePatchBuilder {
	b.patch["sender_agent_id"] = v
	return b
}

func (b *AgentMessagePatchBuilder) SenderName(v string) *AgentMessagePatchBuilder {
	b.patch["sender_name"] = v
	return b
}

func (b *AgentMessagePatchBuilder) SenderUserID(v string) *AgentMessagePatchBuilder {
	b.patch["sender_user_id"] = v
	return b
}


func (b *AgentMessagePatchBuilder) Build() map[string]any {
	return b.patch
}

