// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 47119590c5b99c8ae2cf4280c6cd43829ffd283a58c334f22ff8aedc01851068
// Generated: 2026-02-26T15:25:39Z

package types

type ListOptions struct {
	Page    int
	Size    int
	Search  string
	OrderBy string
	Fields  string
}

type ListOptionsBuilder struct {
	opts ListOptions
}

func NewListOptions() *ListOptionsBuilder {
	return &ListOptionsBuilder{opts: ListOptions{Page: 1, Size: 100}}
}

func (b *ListOptionsBuilder) Page(page int) *ListOptionsBuilder {
	b.opts.Page = page
	return b
}

func (b *ListOptionsBuilder) Size(size int) *ListOptionsBuilder {
	if size > 65500 {
		size = 65500
	}
	b.opts.Size = size
	return b
}

func (b *ListOptionsBuilder) Search(search string) *ListOptionsBuilder {
	b.opts.Search = search
	return b
}

func (b *ListOptionsBuilder) OrderBy(orderBy string) *ListOptionsBuilder {
	b.opts.OrderBy = orderBy
	return b
}

func (b *ListOptionsBuilder) Fields(fields string) *ListOptionsBuilder {
	b.opts.Fields = fields
	return b
}

func (b *ListOptionsBuilder) Build() *ListOptions {
	return &b.opts
}
