// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package types

import (
	"errors"
	"fmt"
)

type ProjectDocument struct {
	ObjectReference

	Content string `json:"content,omitempty"`
	ProjectID string `json:"project_id"`
	Slug string `json:"slug"`
	Title string `json:"title,omitempty"`
}

type ProjectDocumentList struct {
	ListMeta
	Items []ProjectDocument `json:"items"`
}

func (l *ProjectDocumentList) GetItems() []ProjectDocument { return l.Items }
func (l *ProjectDocumentList) GetTotal() int                  { return l.Total }
func (l *ProjectDocumentList) GetPage() int                   { return l.Page }
func (l *ProjectDocumentList) GetSize() int                   { return l.Size }

type ProjectDocumentBuilder struct {
	resource ProjectDocument
	errors   []error
}

func NewProjectDocumentBuilder() *ProjectDocumentBuilder {
	return &ProjectDocumentBuilder{}
}


func (b *ProjectDocumentBuilder) Content(v string) *ProjectDocumentBuilder {
	b.resource.Content = v
	return b
}

func (b *ProjectDocumentBuilder) ProjectID(v string) *ProjectDocumentBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *ProjectDocumentBuilder) Slug(v string) *ProjectDocumentBuilder {
	b.resource.Slug = v
	return b
}

func (b *ProjectDocumentBuilder) Title(v string) *ProjectDocumentBuilder {
	b.resource.Title = v
	return b
}


func (b *ProjectDocumentBuilder) Build() (*ProjectDocument, error) {
	if b.resource.ProjectID == "" {
		b.errors = append(b.errors, fmt.Errorf("project_id is required"))
	}
	if b.resource.Slug == "" {
		b.errors = append(b.errors, fmt.Errorf("slug is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectDocumentPatchBuilder struct {
	patch map[string]any
}

func NewProjectDocumentPatchBuilder() *ProjectDocumentPatchBuilder {
	return &ProjectDocumentPatchBuilder{patch: make(map[string]any)}
}


func (b *ProjectDocumentPatchBuilder) Content(v string) *ProjectDocumentPatchBuilder {
	b.patch["content"] = v
	return b
}

func (b *ProjectDocumentPatchBuilder) ProjectID(v string) *ProjectDocumentPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *ProjectDocumentPatchBuilder) Slug(v string) *ProjectDocumentPatchBuilder {
	b.patch["slug"] = v
	return b
}

func (b *ProjectDocumentPatchBuilder) Title(v string) *ProjectDocumentPatchBuilder {
	b.patch["title"] = v
	return b
}


func (b *ProjectDocumentPatchBuilder) Build() map[string]any {
	return b.patch
}

