// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z

package types

import (
	"errors"
	"fmt"
)

type ProjectAgent struct {
	ObjectReference

	Annotations      string `json:"annotations,omitempty"`
	CurrentSessionID string `json:"current_session_id,omitempty"`
	Labels           string `json:"labels,omitempty"`
	Name             string `json:"name"`
	ProjectID        string `json:"project_id"`
	Prompt           string `json:"prompt,omitempty"`
}

type ProjectAgentList struct {
	ListMeta
	Items []ProjectAgent `json:"items"`
}

func (l *ProjectAgentList) GetItems() []ProjectAgent { return l.Items }
func (l *ProjectAgentList) GetTotal() int            { return l.Total }
func (l *ProjectAgentList) GetPage() int             { return l.Page }
func (l *ProjectAgentList) GetSize() int             { return l.Size }

type ProjectAgentBuilder struct {
	resource ProjectAgent
	errors   []error
}

func NewProjectAgentBuilder() *ProjectAgentBuilder {
	return &ProjectAgentBuilder{}
}

func (b *ProjectAgentBuilder) Annotations(v string) *ProjectAgentBuilder {
	b.resource.Annotations = v
	return b
}

func (b *ProjectAgentBuilder) Labels(v string) *ProjectAgentBuilder {
	b.resource.Labels = v
	return b
}

func (b *ProjectAgentBuilder) Name(v string) *ProjectAgentBuilder {
	b.resource.Name = v
	return b
}

func (b *ProjectAgentBuilder) ProjectID(v string) *ProjectAgentBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *ProjectAgentBuilder) Prompt(v string) *ProjectAgentBuilder {
	b.resource.Prompt = v
	return b
}

func (b *ProjectAgentBuilder) Build() (*ProjectAgent, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.ProjectID == "" {
		b.errors = append(b.errors, fmt.Errorf("project_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ProjectAgentPatchBuilder struct {
	patch map[string]any
}

func NewProjectAgentPatchBuilder() *ProjectAgentPatchBuilder {
	return &ProjectAgentPatchBuilder{patch: make(map[string]any)}
}

func (b *ProjectAgentPatchBuilder) Annotations(v string) *ProjectAgentPatchBuilder {
	b.patch["annotations"] = v
	return b
}

func (b *ProjectAgentPatchBuilder) Labels(v string) *ProjectAgentPatchBuilder {
	b.patch["labels"] = v
	return b
}

func (b *ProjectAgentPatchBuilder) Name(v string) *ProjectAgentPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ProjectAgentPatchBuilder) Prompt(v string) *ProjectAgentPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *ProjectAgentPatchBuilder) Build() map[string]any {
	return b.patch
}
