// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package types

import (
	"errors"
	"fmt"
)

type SessionCheckIn struct {
	ObjectReference

	AgentID string `json:"agent_id"`
	Branch string `json:"branch,omitempty"`
	NextSteps string `json:"next_steps,omitempty"`
	Phase string `json:"phase,omitempty"`
	Pr string `json:"pr,omitempty"`
	SessionID string `json:"session_id"`
	Summary string `json:"summary,omitempty"`
	TestCount int32 `json:"test_count,omitempty"`
	Worktree string `json:"worktree,omitempty"`
}

type SessionCheckInList struct {
	ListMeta
	Items []SessionCheckIn `json:"items"`
}

func (l *SessionCheckInList) GetItems() []SessionCheckIn { return l.Items }
func (l *SessionCheckInList) GetTotal() int                  { return l.Total }
func (l *SessionCheckInList) GetPage() int                   { return l.Page }
func (l *SessionCheckInList) GetSize() int                   { return l.Size }

type SessionCheckInBuilder struct {
	resource SessionCheckIn
	errors   []error
}

func NewSessionCheckInBuilder() *SessionCheckInBuilder {
	return &SessionCheckInBuilder{}
}


func (b *SessionCheckInBuilder) AgentID(v string) *SessionCheckInBuilder {
	b.resource.AgentID = v
	return b
}

func (b *SessionCheckInBuilder) Branch(v string) *SessionCheckInBuilder {
	b.resource.Branch = v
	return b
}

func (b *SessionCheckInBuilder) NextSteps(v string) *SessionCheckInBuilder {
	b.resource.NextSteps = v
	return b
}

func (b *SessionCheckInBuilder) Phase(v string) *SessionCheckInBuilder {
	b.resource.Phase = v
	return b
}

func (b *SessionCheckInBuilder) Pr(v string) *SessionCheckInBuilder {
	b.resource.Pr = v
	return b
}

func (b *SessionCheckInBuilder) SessionID(v string) *SessionCheckInBuilder {
	b.resource.SessionID = v
	return b
}

func (b *SessionCheckInBuilder) Summary(v string) *SessionCheckInBuilder {
	b.resource.Summary = v
	return b
}

func (b *SessionCheckInBuilder) TestCount(v int32) *SessionCheckInBuilder {
	b.resource.TestCount = v
	return b
}

func (b *SessionCheckInBuilder) Worktree(v string) *SessionCheckInBuilder {
	b.resource.Worktree = v
	return b
}


func (b *SessionCheckInBuilder) Build() (*SessionCheckIn, error) {
	if b.resource.AgentID == "" {
		b.errors = append(b.errors, fmt.Errorf("agent_id is required"))
	}
	if b.resource.SessionID == "" {
		b.errors = append(b.errors, fmt.Errorf("session_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SessionCheckInPatchBuilder struct {
	patch map[string]any
}

func NewSessionCheckInPatchBuilder() *SessionCheckInPatchBuilder {
	return &SessionCheckInPatchBuilder{patch: make(map[string]any)}
}


func (b *SessionCheckInPatchBuilder) AgentID(v string) *SessionCheckInPatchBuilder {
	b.patch["agent_id"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) Branch(v string) *SessionCheckInPatchBuilder {
	b.patch["branch"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) NextSteps(v string) *SessionCheckInPatchBuilder {
	b.patch["next_steps"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) Phase(v string) *SessionCheckInPatchBuilder {
	b.patch["phase"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) Pr(v string) *SessionCheckInPatchBuilder {
	b.patch["pr"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) SessionID(v string) *SessionCheckInPatchBuilder {
	b.patch["session_id"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) Summary(v string) *SessionCheckInPatchBuilder {
	b.patch["summary"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) TestCount(v int32) *SessionCheckInPatchBuilder {
	b.patch["test_count"] = v
	return b
}

func (b *SessionCheckInPatchBuilder) Worktree(v string) *SessionCheckInPatchBuilder {
	b.patch["worktree"] = v
	return b
}


func (b *SessionCheckInPatchBuilder) Build() map[string]any {
	return b.patch
}

