queue_rules:
  - name: default
    autoqueue: true
    merge_method: squash
    queue_conditions:
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - check-success=End-to-End Tests
      - commented-reviews-by=coderabbitai[bot]
      - check-success=validate-manifests
      - check-success=test-local-dev-simulation
