- op: add
  path: /spec/template/spec/containers/0/command/-
  value: --api-client-id-file=/secrets/service/clientId
- op: add
  path: /spec/template/spec/containers/0/command/-
  value: --api-client-secret-file=/secrets/service/clientSecret
