# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: /home/mturansk/projects/src/github.com/ambient/platform/components/ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 27ef174cf2467464266e7bfc9d0aa30984a2ad917d93fdaded13f563c44af739
# Generated: 2026-02-24T20:49:14Z

"""Ambient Platform SDK for Python."""

from .client import AmbientClient
from ._base import APIError, ListOptions
from .project import Project, ProjectPatch
from .project_settings import ProjectSettings, ProjectSettingsPatch
from .session import Session, SessionPatch, SessionStatusPatch
from .user import User, UserPatch

__version__ = "1.0.0"

__all__ = [
    "AmbientClient",
    "APIError", 
    "ListOptions",
    "Project",
    "ProjectPatch",
    "ProjectSettings",
    "ProjectSettingsPatch",
    "Session",
    "SessionPatch",
    "SessionStatusPatch",
    "User",
    "UserPatch",
]