# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
# Generated: 2026-03-12T10:28:42Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .agent_message import AgentMessage, AgentMessageList

if TYPE_CHECKING:
    from .client import AmbientClient


class AgentMessageAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> AgentMessage:
        resp = self._client._request("POST", "/agent_messages", json=data)
        return AgentMessage.from_dict(resp)

    def get(self, resource_id: str) -> AgentMessage:
        resp = self._client._request("GET", f"/agent_messages/{resource_id}")
        return AgentMessage.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> AgentMessageList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/agent_messages", params=params)
        return AgentMessageList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> AgentMessage:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/agent_messages/{resource_id}", json=data)
        return AgentMessage.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[AgentMessage]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
