# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z
# NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .inbox_message import InboxMessage, InboxMessageList

if TYPE_CHECKING:
    from .client import AmbientClient


class InboxMessageAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def send(self, project_id: str, pa_id: str, data: dict) -> InboxMessage:
        resp = self._client._request("POST", f"/projects/{project_id}/agents/{pa_id}/inbox", json=data)
        return InboxMessage.from_dict(resp)

    def list(self, project_id: str, pa_id: str, opts: Optional[ListOptions] = None) -> InboxMessageList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", f"/projects/{project_id}/agents/{pa_id}/inbox", params=params)
        return InboxMessageList.from_dict(resp)

    def list_all(self, project_id: str, pa_id: str, size: int = 100, **kwargs: Any) -> Iterator[InboxMessage]:
        page = 1
        while True:
            result = self.list(project_id, pa_id, ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1

    def mark_read(self, project_id: str, pa_id: str, msg_id: str) -> InboxMessage:
        resp = self._client._request("PATCH", f"/projects/{project_id}/agents/{pa_id}/inbox/{msg_id}", json={"read": True})
        return InboxMessage.from_dict(resp)

    def delete(self, project_id: str, pa_id: str, msg_id: str) -> None:
        self._client._request("DELETE", f"/projects/{project_id}/agents/{pa_id}/inbox/{msg_id}", expect_json=False)
