# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: aa4fadb1f795265128f058fdc5ffa2bd25396c8516537ea97ba3671dc007b8fc
# Generated: 2026-06-11T02:31:17Z

from __future__ import annotations

from typing import Any, Callable, Iterator, TypeVar

T = TypeVar("T")


def paginate(fetch_page: Callable[..., Any], size: int = 100) -> Iterator[Any]:
    page = 1
    while True:
        result = fetch_page(page=page, size=size)
        yield from result.items
        if page * size >= result.total:
            break
        page += 1
