# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
# Generated: 2026-03-21T21:30:53Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .project_agent import ProjectAgent, ProjectAgentList

if TYPE_CHECKING:
    from .client import AmbientClient


class ProjectAgentAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> ProjectAgent:
        resp = self._client._request("POST", "/projects", json=data)
        return ProjectAgent.from_dict(resp)

    def get(self, resource_id: str) -> ProjectAgent:
        resp = self._client._request("GET", f"/projects/{resource_id}")
        return ProjectAgent.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ProjectAgentList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/projects", params=params)
        return ProjectAgentList.from_dict(resp)
    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[ProjectAgent]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
