# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z
# NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .project_agent import ProjectAgent, ProjectAgentList
from .session import SessionList

if TYPE_CHECKING:
    from .client import AmbientClient


@dataclass(frozen=True)
class IgniteRequest:
    prompt: str = ""

    def to_dict(self) -> dict:
        return {"prompt": self.prompt} if self.prompt else {}


@dataclass(frozen=True)
class IgniteResponse:
    session: Optional[Any] = None
    ignition_context: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> IgniteResponse:
        from .session import Session
        session_data = data.get("session")
        return cls(
            session=Session.from_dict(session_data) if session_data else None,
            ignition_context=data.get("ignition_context", ""),
        )


class ProjectAgentAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, project_id: str, data: dict) -> ProjectAgent:
        resp = self._client._request("POST", f"/projects/{project_id}/agents", json=data)
        return ProjectAgent.from_dict(resp)

    def get(self, project_id: str, pa_id: str) -> ProjectAgent:
        resp = self._client._request("GET", f"/projects/{project_id}/agents/{pa_id}")
        return ProjectAgent.from_dict(resp)

    def list(self, project_id: str, opts: Optional[ListOptions] = None) -> ProjectAgentList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", f"/projects/{project_id}/agents", params=params)
        return ProjectAgentList.from_dict(resp)

    def list_all(self, project_id: str, size: int = 100, **kwargs: Any) -> Iterator[ProjectAgent]:
        page = 1
        while True:
            result = self.list(project_id, ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1

    def update(self, project_id: str, pa_id: str, patch: dict) -> ProjectAgent:
        resp = self._client._request("PATCH", f"/projects/{project_id}/agents/{pa_id}", json=patch)
        return ProjectAgent.from_dict(resp)

    def delete(self, project_id: str, pa_id: str) -> None:
        self._client._request("DELETE", f"/projects/{project_id}/agents/{pa_id}", expect_json=False)

    def ignite(self, project_id: str, pa_id: str, prompt: str = "") -> IgniteResponse:
        body = {"prompt": prompt} if prompt else {}
        resp = self._client._request("POST", f"/projects/{project_id}/agents/{pa_id}/ignite", json=body)
        return IgniteResponse.from_dict(resp)

    def get_ignition(self, project_id: str, pa_id: str) -> IgniteResponse:
        resp = self._client._request("GET", f"/projects/{project_id}/agents/{pa_id}/ignition")
        return IgniteResponse.from_dict(resp)

    def sessions(self, project_id: str, pa_id: str, opts: Optional[ListOptions] = None) -> SessionList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", f"/projects/{project_id}/agents/{pa_id}/sessions", params=params)
        return SessionList.from_dict(resp)
