# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 47119590c5b99c8ae2cf4280c6cd43829ffd283a58c334f22ff8aedc01851068
# Generated: 2026-02-26T15:25:39Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .project_settings import ProjectSettings, ProjectSettingsList

if TYPE_CHECKING:
    from .client import AmbientClient


class ProjectSettingsAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> ProjectSettings:
        resp = self._client._request("POST", "/project_settings", json=data)
        return ProjectSettings.from_dict(resp)

    def get(self, resource_id: str) -> ProjectSettings:
        resp = self._client._request("GET", f"/project_settings/{resource_id}")
        return ProjectSettings.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ProjectSettingsList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/project_settings", params=params)
        return ProjectSettingsList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> ProjectSettings:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/project_settings/{resource_id}", json=data)
        return ProjectSettings.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/project_settings/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[ProjectSettings]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
