# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
# Generated: 2026-03-10T14:18:34Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .project_document import ProjectDocument, ProjectDocumentList

if TYPE_CHECKING:
    from .client import AmbientClient


class ProjectDocumentAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> ProjectDocument:
        resp = self._client._request("POST", "/project_documents", json=data)
        return ProjectDocument.from_dict(resp)

    def get(self, resource_id: str) -> ProjectDocument:
        resp = self._client._request("GET", f"/project_documents/{resource_id}")
        return ProjectDocument.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ProjectDocumentList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/project_documents", params=params)
        return ProjectDocumentList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> ProjectDocument:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/project_documents/{resource_id}", json=data)
        return ProjectDocument.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[ProjectDocument]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
