# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z
# NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .session_message import SessionMessage, SessionMessageList

if TYPE_CHECKING:
    from .client import AmbientClient


class SessionMessageAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def list(self, session_id: str, opts: Optional[ListOptions] = None) -> SessionMessageList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", f"/sessions/{session_id}/messages", params=params)
        return SessionMessageList.from_dict(resp)

    def list_all(self, session_id: str, size: int = 100, **kwargs: Any) -> Iterator[SessionMessage]:
        page = 1
        while True:
            result = self.list(session_id, ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
