# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: f0ec84178602f3437cc365a1e354b5286dbd72ff5c138db499664f62b927bb61
# Generated: 2026-02-28T15:30:52Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .user import User, UserList

if TYPE_CHECKING:
    from .client import AmbientClient


class UserAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> User:
        resp = self._client._request("POST", "/users", json=data)
        return User.from_dict(resp)

    def get(self, resource_id: str) -> User:
        resp = self._client._request("GET", f"/users/{resource_id}")
        return User.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> UserList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/users", params=params)
        return UserList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> User:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/users/{resource_id}", json=data)
        return User.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[User]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
