# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
# Generated: 2026-03-12T10:28:42Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class AGUIEvent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    event_type: str = ""
    payload: str = ""
    seq: int = 0
    session_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> AGUIEvent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            event_type=data.get("event_type", ""),
            payload=data.get("payload", ""),
            seq=data.get("seq", 0),
            session_id=data.get("session_id", ""),
        )

    @classmethod
    def builder(cls) -> AGUIEventBuilder:
        return AGUIEventBuilder()


@dataclass(frozen=True)
class AGUIEventList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[AGUIEvent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> AGUIEventList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[AGUIEvent.from_dict(item) for item in data.get("items", [])],
        )


class AGUIEventBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def event_type(self, value: str) -> AGUIEventBuilder:
        self._data["event_type"] = value
        return self

    def payload(self, value: str) -> AGUIEventBuilder:
        self._data["payload"] = value
        return self

    def seq(self, value: int) -> AGUIEventBuilder:
        self._data["seq"] = value
        return self

    def session_id(self, value: str) -> AGUIEventBuilder:
        self._data["session_id"] = value
        return self

    def build(self) -> dict:
        if "event_type" not in self._data:
            raise ValueError("event_type is required")
        if "session_id" not in self._data:
            raise ValueError("session_id is required")
        return dict(self._data)


class AGUIEventPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def event_type(self, value: str) -> AGUIEventPatch:
        self._data["event_type"] = value
        return self

    def payload(self, value: str) -> AGUIEventPatch:
        self._data["payload"] = value
        return self

    def seq(self, value: int) -> AGUIEventPatch:
        self._data["seq"] = value
        return self

    def session_id(self, value: str) -> AGUIEventPatch:
        self._data["session_id"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
