# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
# Generated: 2026-03-10T14:18:34Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class AgentMessage:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    body: str = ""
    read: bool = False
    recipient_agent_id: str = ""
    sender_agent_id: str = ""
    sender_name: str = ""
    sender_user_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> AgentMessage:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            body=data.get("body", ""),
            read=data.get("read", False),
            recipient_agent_id=data.get("recipient_agent_id", ""),
            sender_agent_id=data.get("sender_agent_id", ""),
            sender_name=data.get("sender_name", ""),
            sender_user_id=data.get("sender_user_id", ""),
        )

    @classmethod
    def builder(cls) -> AgentMessageBuilder:
        return AgentMessageBuilder()


@dataclass(frozen=True)
class AgentMessageList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[AgentMessage] = ()

    @classmethod
    def from_dict(cls, data: dict) -> AgentMessageList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[AgentMessage.from_dict(item) for item in data.get("items", [])],
        )


class AgentMessageBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def body(self, value: str) -> AgentMessageBuilder:
        self._data["body"] = value
        return self

    def read(self, value: bool) -> AgentMessageBuilder:
        self._data["read"] = value
        return self

    def recipient_agent_id(self, value: str) -> AgentMessageBuilder:
        self._data["recipient_agent_id"] = value
        return self

    def sender_agent_id(self, value: str) -> AgentMessageBuilder:
        self._data["sender_agent_id"] = value
        return self

    def sender_name(self, value: str) -> AgentMessageBuilder:
        self._data["sender_name"] = value
        return self

    def sender_user_id(self, value: str) -> AgentMessageBuilder:
        self._data["sender_user_id"] = value
        return self

    def build(self) -> dict:
        if "recipient_agent_id" not in self._data:
            raise ValueError("recipient_agent_id is required")
        return dict(self._data)


class AgentMessagePatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def body(self, value: str) -> AgentMessagePatch:
        self._data["body"] = value
        return self

    def read(self, value: bool) -> AgentMessagePatch:
        self._data["read"] = value
        return self

    def recipient_agent_id(self, value: str) -> AgentMessagePatch:
        self._data["recipient_agent_id"] = value
        return self

    def sender_agent_id(self, value: str) -> AgentMessagePatch:
        self._data["sender_agent_id"] = value
        return self

    def sender_name(self, value: str) -> AgentMessagePatch:
        self._data["sender_name"] = value
        return self

    def sender_user_id(self, value: str) -> AgentMessagePatch:
        self._data["sender_user_id"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

