# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
# Generated: 2026-03-20T16:48:23Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class ProjectAgent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    agent_id: str = ""
    agent_version: int = 0
    current_session_id: str = ""
    project_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ProjectAgent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            agent_id=data.get("agent_id", ""),
            agent_version=data.get("agent_version", 0),
            current_session_id=data.get("current_session_id", ""),
            project_id=data.get("project_id", ""),
        )

    @classmethod
    def builder(cls) -> ProjectAgentBuilder:
        return ProjectAgentBuilder()


@dataclass(frozen=True)
class ProjectAgentList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[ProjectAgent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectAgentList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[ProjectAgent.from_dict(item) for item in data.get("items", [])],
        )


class ProjectAgentBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def agent_id(self, value: str) -> ProjectAgentBuilder:
        self._data["agent_id"] = value
        return self

    def agent_version(self, value: int) -> ProjectAgentBuilder:
        self._data["agent_version"] = value
        return self

    def project_id(self, value: str) -> ProjectAgentBuilder:
        self._data["project_id"] = value
        return self

    def build(self) -> dict:
        if "agent_id" not in self._data:
            raise ValueError("agent_id is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class ProjectAgentPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def agent_version(self, value: int) -> ProjectAgentPatch:
        self._data["agent_version"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
