# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
# Generated: 2026-03-21T21:30:53Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class ProjectAgent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    current_session_id: str = ""
    labels: str = ""
    name: str = ""
    project_id: str = ""
    prompt: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ProjectAgent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            current_session_id=data.get("current_session_id", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            project_id=data.get("project_id", ""),
            prompt=data.get("prompt", ""),
        )

    @classmethod
    def builder(cls) -> ProjectAgentBuilder:
        return ProjectAgentBuilder()


@dataclass(frozen=True)
class ProjectAgentList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[ProjectAgent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectAgentList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[ProjectAgent.from_dict(item) for item in data.get("items", [])],
        )


class ProjectAgentBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectAgentBuilder:
        self._data["annotations"] = value
        return self

    def labels(self, value: str) -> ProjectAgentBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectAgentBuilder:
        self._data["name"] = value
        return self

    def project_id(self, value: str) -> ProjectAgentBuilder:
        self._data["project_id"] = value
        return self

    def prompt(self, value: str) -> ProjectAgentBuilder:
        self._data["prompt"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class ProjectAgentPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectAgentPatch:
        self._data["annotations"] = value
        return self

    def labels(self, value: str) -> ProjectAgentPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectAgentPatch:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> ProjectAgentPatch:
        self._data["prompt"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
