# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
# Generated: 2026-03-12T10:28:42Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class ProjectDocument:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    content: str = ""
    project_id: str = ""
    slug: str = ""
    title: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ProjectDocument:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            content=data.get("content", ""),
            project_id=data.get("project_id", ""),
            slug=data.get("slug", ""),
            title=data.get("title", ""),
        )

    @classmethod
    def builder(cls) -> ProjectDocumentBuilder:
        return ProjectDocumentBuilder()


@dataclass(frozen=True)
class ProjectDocumentList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[ProjectDocument] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectDocumentList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[ProjectDocument.from_dict(item) for item in data.get("items", [])],
        )


class ProjectDocumentBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def content(self, value: str) -> ProjectDocumentBuilder:
        self._data["content"] = value
        return self

    def project_id(self, value: str) -> ProjectDocumentBuilder:
        self._data["project_id"] = value
        return self

    def slug(self, value: str) -> ProjectDocumentBuilder:
        self._data["slug"] = value
        return self

    def title(self, value: str) -> ProjectDocumentBuilder:
        self._data["title"] = value
        return self

    def build(self) -> dict:
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        if "slug" not in self._data:
            raise ValueError("slug is required")
        return dict(self._data)


class ProjectDocumentPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def content(self, value: str) -> ProjectDocumentPatch:
        self._data["content"] = value
        return self

    def project_id(self, value: str) -> ProjectDocumentPatch:
        self._data["project_id"] = value
        return self

    def slug(self, value: str) -> ProjectDocumentPatch:
        self._data["slug"] = value
        return self

    def title(self, value: str) -> ProjectDocumentPatch:
        self._data["title"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
