# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
# Generated: 2026-03-10T14:18:34Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class SessionCheckIn:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    agent_id: str = ""
    branch: str = ""
    next_steps: str = ""
    phase: str = ""
    pr: str = ""
    session_id: str = ""
    summary: str = ""
    test_count: int = 0
    worktree: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> SessionCheckIn:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            agent_id=data.get("agent_id", ""),
            branch=data.get("branch", ""),
            next_steps=data.get("next_steps", ""),
            phase=data.get("phase", ""),
            pr=data.get("pr", ""),
            session_id=data.get("session_id", ""),
            summary=data.get("summary", ""),
            test_count=data.get("test_count", 0),
            worktree=data.get("worktree", ""),
        )

    @classmethod
    def builder(cls) -> SessionCheckInBuilder:
        return SessionCheckInBuilder()


@dataclass(frozen=True)
class SessionCheckInList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[SessionCheckIn] = ()

    @classmethod
    def from_dict(cls, data: dict) -> SessionCheckInList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[SessionCheckIn.from_dict(item) for item in data.get("items", [])],
        )


class SessionCheckInBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def agent_id(self, value: str) -> SessionCheckInBuilder:
        self._data["agent_id"] = value
        return self

    def branch(self, value: str) -> SessionCheckInBuilder:
        self._data["branch"] = value
        return self

    def next_steps(self, value: str) -> SessionCheckInBuilder:
        self._data["next_steps"] = value
        return self

    def phase(self, value: str) -> SessionCheckInBuilder:
        self._data["phase"] = value
        return self

    def pr(self, value: str) -> SessionCheckInBuilder:
        self._data["pr"] = value
        return self

    def session_id(self, value: str) -> SessionCheckInBuilder:
        self._data["session_id"] = value
        return self

    def summary(self, value: str) -> SessionCheckInBuilder:
        self._data["summary"] = value
        return self

    def test_count(self, value: int) -> SessionCheckInBuilder:
        self._data["test_count"] = value
        return self

    def worktree(self, value: str) -> SessionCheckInBuilder:
        self._data["worktree"] = value
        return self

    def build(self) -> dict:
        if "agent_id" not in self._data:
            raise ValueError("agent_id is required")
        if "session_id" not in self._data:
            raise ValueError("session_id is required")
        return dict(self._data)


class SessionCheckInPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def agent_id(self, value: str) -> SessionCheckInPatch:
        self._data["agent_id"] = value
        return self

    def branch(self, value: str) -> SessionCheckInPatch:
        self._data["branch"] = value
        return self

    def next_steps(self, value: str) -> SessionCheckInPatch:
        self._data["next_steps"] = value
        return self

    def phase(self, value: str) -> SessionCheckInPatch:
        self._data["phase"] = value
        return self

    def pr(self, value: str) -> SessionCheckInPatch:
        self._data["pr"] = value
        return self

    def session_id(self, value: str) -> SessionCheckInPatch:
        self._data["session_id"] = value
        return self

    def summary(self, value: str) -> SessionCheckInPatch:
        self._data["summary"] = value
        return self

    def test_count(self, value: int) -> SessionCheckInPatch:
        self._data["test_count"] = value
        return self

    def worktree(self, value: str) -> SessionCheckInPatch:
        self._data["worktree"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)

