/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the StartResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &StartResponse{}

// StartResponse struct for StartResponse
type StartResponse struct {
	Session *Session `json:"session,omitempty"`
	// Assembled start prompt — Agent.prompt + Inbox + Session.prompt + peer roster
	StartingPrompt *string `json:"starting_prompt,omitempty"`
}

// NewStartResponse instantiates a new StartResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewStartResponse() *StartResponse {
	this := StartResponse{}
	return &this
}

// NewStartResponseWithDefaults instantiates a new StartResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewStartResponseWithDefaults() *StartResponse {
	this := StartResponse{}
	return &this
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *StartResponse) GetSession() Session {
	if o == nil || IsNil(o.Session) {
		var ret Session
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartResponse) GetSessionOk() (*Session, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *StartResponse) HasSession() bool {
	if o != nil && !IsNil(o.Session) {
		return true
	}

	return false
}

// SetSession gets a reference to the given Session and assigns it to the Session field.
func (o *StartResponse) SetSession(v Session) {
	o.Session = &v
}

// GetStartingPrompt returns the StartingPrompt field value if set, zero value otherwise.
func (o *StartResponse) GetStartingPrompt() string {
	if o == nil || IsNil(o.StartingPrompt) {
		var ret string
		return ret
	}
	return *o.StartingPrompt
}

// GetStartingPromptOk returns a tuple with the StartingPrompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *StartResponse) GetStartingPromptOk() (*string, bool) {
	if o == nil || IsNil(o.StartingPrompt) {
		return nil, false
	}
	return o.StartingPrompt, true
}

// HasStartingPrompt returns a boolean if a field has been set.
func (o *StartResponse) HasStartingPrompt() bool {
	if o != nil && !IsNil(o.StartingPrompt) {
		return true
	}

	return false
}

// SetStartingPrompt gets a reference to the given string and assigns it to the StartingPrompt field.
func (o *StartResponse) SetStartingPrompt(v string) {
	o.StartingPrompt = &v
}

func (o StartResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o StartResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Session) {
		toSerialize["session"] = o.Session
	}
	if !IsNil(o.StartingPrompt) {
		toSerialize["starting_prompt"] = o.StartingPrompt
	}
	return toSerialize, nil
}

type NullableStartResponse struct {
	value *StartResponse
	isSet bool
}

func (v NullableStartResponse) Get() *StartResponse {
	return v.value
}

func (v *NullableStartResponse) Set(val *StartResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableStartResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableStartResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableStartResponse(val *StartResponse) *NullableStartResponse {
	return &NullableStartResponse{value: val, isSet: true}
}

func (v NullableStartResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableStartResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
