/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentMessagePatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMessagePatchRequest{}

// AgentMessagePatchRequest struct for AgentMessagePatchRequest
type AgentMessagePatchRequest struct {
	RecipientAgentId *string `json:"recipient_agent_id,omitempty"`
	SenderAgentId    *string `json:"sender_agent_id,omitempty"`
	SenderUserId     *string `json:"sender_user_id,omitempty"`
	SenderName       *string `json:"sender_name,omitempty"`
	Body             *string `json:"body,omitempty"`
	Read             *bool   `json:"read,omitempty"`
}

// NewAgentMessagePatchRequest instantiates a new AgentMessagePatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMessagePatchRequest() *AgentMessagePatchRequest {
	this := AgentMessagePatchRequest{}
	return &this
}

// NewAgentMessagePatchRequestWithDefaults instantiates a new AgentMessagePatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMessagePatchRequestWithDefaults() *AgentMessagePatchRequest {
	this := AgentMessagePatchRequest{}
	return &this
}

// GetRecipientAgentId returns the RecipientAgentId field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetRecipientAgentId() string {
	if o == nil || IsNil(o.RecipientAgentId) {
		var ret string
		return ret
	}
	return *o.RecipientAgentId
}

// GetRecipientAgentIdOk returns a tuple with the RecipientAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetRecipientAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.RecipientAgentId) {
		return nil, false
	}
	return o.RecipientAgentId, true
}

// HasRecipientAgentId returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasRecipientAgentId() bool {
	if o != nil && !IsNil(o.RecipientAgentId) {
		return true
	}

	return false
}

// SetRecipientAgentId gets a reference to the given string and assigns it to the RecipientAgentId field.
func (o *AgentMessagePatchRequest) SetRecipientAgentId(v string) {
	o.RecipientAgentId = &v
}

// GetSenderAgentId returns the SenderAgentId field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetSenderAgentId() string {
	if o == nil || IsNil(o.SenderAgentId) {
		var ret string
		return ret
	}
	return *o.SenderAgentId
}

// GetSenderAgentIdOk returns a tuple with the SenderAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetSenderAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.SenderAgentId) {
		return nil, false
	}
	return o.SenderAgentId, true
}

// HasSenderAgentId returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasSenderAgentId() bool {
	if o != nil && !IsNil(o.SenderAgentId) {
		return true
	}

	return false
}

// SetSenderAgentId gets a reference to the given string and assigns it to the SenderAgentId field.
func (o *AgentMessagePatchRequest) SetSenderAgentId(v string) {
	o.SenderAgentId = &v
}

// GetSenderUserId returns the SenderUserId field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetSenderUserId() string {
	if o == nil || IsNil(o.SenderUserId) {
		var ret string
		return ret
	}
	return *o.SenderUserId
}

// GetSenderUserIdOk returns a tuple with the SenderUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetSenderUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.SenderUserId) {
		return nil, false
	}
	return o.SenderUserId, true
}

// HasSenderUserId returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasSenderUserId() bool {
	if o != nil && !IsNil(o.SenderUserId) {
		return true
	}

	return false
}

// SetSenderUserId gets a reference to the given string and assigns it to the SenderUserId field.
func (o *AgentMessagePatchRequest) SetSenderUserId(v string) {
	o.SenderUserId = &v
}

// GetSenderName returns the SenderName field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetSenderName() string {
	if o == nil || IsNil(o.SenderName) {
		var ret string
		return ret
	}
	return *o.SenderName
}

// GetSenderNameOk returns a tuple with the SenderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetSenderNameOk() (*string, bool) {
	if o == nil || IsNil(o.SenderName) {
		return nil, false
	}
	return o.SenderName, true
}

// HasSenderName returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasSenderName() bool {
	if o != nil && !IsNil(o.SenderName) {
		return true
	}

	return false
}

// SetSenderName gets a reference to the given string and assigns it to the SenderName field.
func (o *AgentMessagePatchRequest) SetSenderName(v string) {
	o.SenderName = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *AgentMessagePatchRequest) SetBody(v string) {
	o.Body = &v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *AgentMessagePatchRequest) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessagePatchRequest) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *AgentMessagePatchRequest) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *AgentMessagePatchRequest) SetRead(v bool) {
	o.Read = &v
}

func (o AgentMessagePatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMessagePatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RecipientAgentId) {
		toSerialize["recipient_agent_id"] = o.RecipientAgentId
	}
	if !IsNil(o.SenderAgentId) {
		toSerialize["sender_agent_id"] = o.SenderAgentId
	}
	if !IsNil(o.SenderUserId) {
		toSerialize["sender_user_id"] = o.SenderUserId
	}
	if !IsNil(o.SenderName) {
		toSerialize["sender_name"] = o.SenderName
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	return toSerialize, nil
}

type NullableAgentMessagePatchRequest struct {
	value *AgentMessagePatchRequest
	isSet bool
}

func (v NullableAgentMessagePatchRequest) Get() *AgentMessagePatchRequest {
	return v.value
}

func (v *NullableAgentMessagePatchRequest) Set(val *AgentMessagePatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMessagePatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMessagePatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMessagePatchRequest(val *AgentMessagePatchRequest) *NullableAgentMessagePatchRequest {
	return &NullableAgentMessagePatchRequest{value: val, isSet: true}
}

func (v NullableAgentMessagePatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMessagePatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
