/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the AgentMessage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMessage{}

// AgentMessage struct for AgentMessage
type AgentMessage struct {
	Id               *string    `json:"id,omitempty"`
	Kind             *string    `json:"kind,omitempty"`
	Href             *string    `json:"href,omitempty"`
	CreatedAt        *time.Time `json:"created_at,omitempty"`
	UpdatedAt        *time.Time `json:"updated_at,omitempty"`
	RecipientAgentId string     `json:"recipient_agent_id"`
	SenderAgentId    *string    `json:"sender_agent_id,omitempty"`
	SenderUserId     *string    `json:"sender_user_id,omitempty"`
	SenderName       *string    `json:"sender_name,omitempty"`
	Body             *string    `json:"body,omitempty"`
	Read             *bool      `json:"read,omitempty"`
}

type _AgentMessage AgentMessage

// NewAgentMessage instantiates a new AgentMessage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMessage(recipientAgentId string) *AgentMessage {
	this := AgentMessage{}
	this.RecipientAgentId = recipientAgentId
	return &this
}

// NewAgentMessageWithDefaults instantiates a new AgentMessage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMessageWithDefaults() *AgentMessage {
	this := AgentMessage{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentMessage) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentMessage) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentMessage) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *AgentMessage) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *AgentMessage) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *AgentMessage) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *AgentMessage) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *AgentMessage) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *AgentMessage) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentMessage) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentMessage) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AgentMessage) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AgentMessage) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AgentMessage) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AgentMessage) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetRecipientAgentId returns the RecipientAgentId field value
func (o *AgentMessage) GetRecipientAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RecipientAgentId
}

// GetRecipientAgentIdOk returns a tuple with the RecipientAgentId field value
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetRecipientAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RecipientAgentId, true
}

// SetRecipientAgentId sets field value
func (o *AgentMessage) SetRecipientAgentId(v string) {
	o.RecipientAgentId = v
}

// GetSenderAgentId returns the SenderAgentId field value if set, zero value otherwise.
func (o *AgentMessage) GetSenderAgentId() string {
	if o == nil || IsNil(o.SenderAgentId) {
		var ret string
		return ret
	}
	return *o.SenderAgentId
}

// GetSenderAgentIdOk returns a tuple with the SenderAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetSenderAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.SenderAgentId) {
		return nil, false
	}
	return o.SenderAgentId, true
}

// HasSenderAgentId returns a boolean if a field has been set.
func (o *AgentMessage) HasSenderAgentId() bool {
	if o != nil && !IsNil(o.SenderAgentId) {
		return true
	}

	return false
}

// SetSenderAgentId gets a reference to the given string and assigns it to the SenderAgentId field.
func (o *AgentMessage) SetSenderAgentId(v string) {
	o.SenderAgentId = &v
}

// GetSenderUserId returns the SenderUserId field value if set, zero value otherwise.
func (o *AgentMessage) GetSenderUserId() string {
	if o == nil || IsNil(o.SenderUserId) {
		var ret string
		return ret
	}
	return *o.SenderUserId
}

// GetSenderUserIdOk returns a tuple with the SenderUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetSenderUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.SenderUserId) {
		return nil, false
	}
	return o.SenderUserId, true
}

// HasSenderUserId returns a boolean if a field has been set.
func (o *AgentMessage) HasSenderUserId() bool {
	if o != nil && !IsNil(o.SenderUserId) {
		return true
	}

	return false
}

// SetSenderUserId gets a reference to the given string and assigns it to the SenderUserId field.
func (o *AgentMessage) SetSenderUserId(v string) {
	o.SenderUserId = &v
}

// GetSenderName returns the SenderName field value if set, zero value otherwise.
func (o *AgentMessage) GetSenderName() string {
	if o == nil || IsNil(o.SenderName) {
		var ret string
		return ret
	}
	return *o.SenderName
}

// GetSenderNameOk returns a tuple with the SenderName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetSenderNameOk() (*string, bool) {
	if o == nil || IsNil(o.SenderName) {
		return nil, false
	}
	return o.SenderName, true
}

// HasSenderName returns a boolean if a field has been set.
func (o *AgentMessage) HasSenderName() bool {
	if o != nil && !IsNil(o.SenderName) {
		return true
	}

	return false
}

// SetSenderName gets a reference to the given string and assigns it to the SenderName field.
func (o *AgentMessage) SetSenderName(v string) {
	o.SenderName = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *AgentMessage) GetBody() string {
	if o == nil || IsNil(o.Body) {
		var ret string
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetBodyOk() (*string, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *AgentMessage) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given string and assigns it to the Body field.
func (o *AgentMessage) SetBody(v string) {
	o.Body = &v
}

// GetRead returns the Read field value if set, zero value otherwise.
func (o *AgentMessage) GetRead() bool {
	if o == nil || IsNil(o.Read) {
		var ret bool
		return ret
	}
	return *o.Read
}

// GetReadOk returns a tuple with the Read field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentMessage) GetReadOk() (*bool, bool) {
	if o == nil || IsNil(o.Read) {
		return nil, false
	}
	return o.Read, true
}

// HasRead returns a boolean if a field has been set.
func (o *AgentMessage) HasRead() bool {
	if o != nil && !IsNil(o.Read) {
		return true
	}

	return false
}

// SetRead gets a reference to the given bool and assigns it to the Read field.
func (o *AgentMessage) SetRead(v bool) {
	o.Read = &v
}

func (o AgentMessage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMessage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["recipient_agent_id"] = o.RecipientAgentId
	if !IsNil(o.SenderAgentId) {
		toSerialize["sender_agent_id"] = o.SenderAgentId
	}
	if !IsNil(o.SenderUserId) {
		toSerialize["sender_user_id"] = o.SenderUserId
	}
	if !IsNil(o.SenderName) {
		toSerialize["sender_name"] = o.SenderName
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	if !IsNil(o.Read) {
		toSerialize["read"] = o.Read
	}
	return toSerialize, nil
}

func (o *AgentMessage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"recipient_agent_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentMessage := _AgentMessage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentMessage)

	if err != nil {
		return err
	}

	*o = AgentMessage(varAgentMessage)

	return err
}

type NullableAgentMessage struct {
	value *AgentMessage
	isSet bool
}

func (v NullableAgentMessage) Get() *AgentMessage {
	return v.value
}

func (v *NullableAgentMessage) Set(val *AgentMessage) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMessage) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMessage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMessage(val *AgentMessage) *NullableAgentMessage {
	return &NullableAgentMessage{value: val, isSet: true}
}

func (v NullableAgentMessage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMessage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
