/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the SessionCheckIn type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionCheckIn{}

// SessionCheckIn struct for SessionCheckIn
type SessionCheckIn struct {
	Id        *string    `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	Href      *string    `json:"href,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	SessionId string     `json:"session_id"`
	AgentId   string     `json:"agent_id"`
	Summary   *string    `json:"summary,omitempty"`
	Branch    *string    `json:"branch,omitempty"`
	Worktree  *string    `json:"worktree,omitempty"`
	Pr        *string    `json:"pr,omitempty"`
	Phase     *string    `json:"phase,omitempty"`
	TestCount *int32     `json:"test_count,omitempty"`
	NextSteps *string    `json:"next_steps,omitempty"`
}

type _SessionCheckIn SessionCheckIn

// NewSessionCheckIn instantiates a new SessionCheckIn object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionCheckIn(sessionId string, agentId string) *SessionCheckIn {
	this := SessionCheckIn{}
	this.SessionId = sessionId
	this.AgentId = agentId
	return &this
}

// NewSessionCheckInWithDefaults instantiates a new SessionCheckIn object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionCheckInWithDefaults() *SessionCheckIn {
	this := SessionCheckIn{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SessionCheckIn) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SessionCheckIn) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SessionCheckIn) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *SessionCheckIn) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *SessionCheckIn) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *SessionCheckIn) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *SessionCheckIn) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *SessionCheckIn) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *SessionCheckIn) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *SessionCheckIn) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *SessionCheckIn) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *SessionCheckIn) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *SessionCheckIn) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *SessionCheckIn) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *SessionCheckIn) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetSessionId returns the SessionId field value
func (o *SessionCheckIn) GetSessionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetSessionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SessionId, true
}

// SetSessionId sets field value
func (o *SessionCheckIn) SetSessionId(v string) {
	o.SessionId = v
}

// GetAgentId returns the AgentId field value
func (o *SessionCheckIn) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *SessionCheckIn) SetAgentId(v string) {
	o.AgentId = v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *SessionCheckIn) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *SessionCheckIn) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *SessionCheckIn) SetSummary(v string) {
	o.Summary = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *SessionCheckIn) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *SessionCheckIn) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *SessionCheckIn) SetBranch(v string) {
	o.Branch = &v
}

// GetWorktree returns the Worktree field value if set, zero value otherwise.
func (o *SessionCheckIn) GetWorktree() string {
	if o == nil || IsNil(o.Worktree) {
		var ret string
		return ret
	}
	return *o.Worktree
}

// GetWorktreeOk returns a tuple with the Worktree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetWorktreeOk() (*string, bool) {
	if o == nil || IsNil(o.Worktree) {
		return nil, false
	}
	return o.Worktree, true
}

// HasWorktree returns a boolean if a field has been set.
func (o *SessionCheckIn) HasWorktree() bool {
	if o != nil && !IsNil(o.Worktree) {
		return true
	}

	return false
}

// SetWorktree gets a reference to the given string and assigns it to the Worktree field.
func (o *SessionCheckIn) SetWorktree(v string) {
	o.Worktree = &v
}

// GetPr returns the Pr field value if set, zero value otherwise.
func (o *SessionCheckIn) GetPr() string {
	if o == nil || IsNil(o.Pr) {
		var ret string
		return ret
	}
	return *o.Pr
}

// GetPrOk returns a tuple with the Pr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetPrOk() (*string, bool) {
	if o == nil || IsNil(o.Pr) {
		return nil, false
	}
	return o.Pr, true
}

// HasPr returns a boolean if a field has been set.
func (o *SessionCheckIn) HasPr() bool {
	if o != nil && !IsNil(o.Pr) {
		return true
	}

	return false
}

// SetPr gets a reference to the given string and assigns it to the Pr field.
func (o *SessionCheckIn) SetPr(v string) {
	o.Pr = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *SessionCheckIn) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *SessionCheckIn) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *SessionCheckIn) SetPhase(v string) {
	o.Phase = &v
}

// GetTestCount returns the TestCount field value if set, zero value otherwise.
func (o *SessionCheckIn) GetTestCount() int32 {
	if o == nil || IsNil(o.TestCount) {
		var ret int32
		return ret
	}
	return *o.TestCount
}

// GetTestCountOk returns a tuple with the TestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TestCount) {
		return nil, false
	}
	return o.TestCount, true
}

// HasTestCount returns a boolean if a field has been set.
func (o *SessionCheckIn) HasTestCount() bool {
	if o != nil && !IsNil(o.TestCount) {
		return true
	}

	return false
}

// SetTestCount gets a reference to the given int32 and assigns it to the TestCount field.
func (o *SessionCheckIn) SetTestCount(v int32) {
	o.TestCount = &v
}

// GetNextSteps returns the NextSteps field value if set, zero value otherwise.
func (o *SessionCheckIn) GetNextSteps() string {
	if o == nil || IsNil(o.NextSteps) {
		var ret string
		return ret
	}
	return *o.NextSteps
}

// GetNextStepsOk returns a tuple with the NextSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckIn) GetNextStepsOk() (*string, bool) {
	if o == nil || IsNil(o.NextSteps) {
		return nil, false
	}
	return o.NextSteps, true
}

// HasNextSteps returns a boolean if a field has been set.
func (o *SessionCheckIn) HasNextSteps() bool {
	if o != nil && !IsNil(o.NextSteps) {
		return true
	}

	return false
}

// SetNextSteps gets a reference to the given string and assigns it to the NextSteps field.
func (o *SessionCheckIn) SetNextSteps(v string) {
	o.NextSteps = &v
}

func (o SessionCheckIn) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionCheckIn) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["session_id"] = o.SessionId
	toSerialize["agent_id"] = o.AgentId
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Worktree) {
		toSerialize["worktree"] = o.Worktree
	}
	if !IsNil(o.Pr) {
		toSerialize["pr"] = o.Pr
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.TestCount) {
		toSerialize["test_count"] = o.TestCount
	}
	if !IsNil(o.NextSteps) {
		toSerialize["next_steps"] = o.NextSteps
	}
	return toSerialize, nil
}

func (o *SessionCheckIn) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"session_id",
		"agent_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSessionCheckIn := _SessionCheckIn{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSessionCheckIn)

	if err != nil {
		return err
	}

	*o = SessionCheckIn(varSessionCheckIn)

	return err
}

type NullableSessionCheckIn struct {
	value *SessionCheckIn
	isSet bool
}

func (v NullableSessionCheckIn) Get() *SessionCheckIn {
	return v.value
}

func (v *NullableSessionCheckIn) Set(val *SessionCheckIn) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionCheckIn) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionCheckIn) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionCheckIn(val *SessionCheckIn) *NullableSessionCheckIn {
	return &NullableSessionCheckIn{value: val, isSet: true}
}

func (v NullableSessionCheckIn) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionCheckIn) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
