/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectDocumentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectDocumentPatchRequest{}

// ProjectDocumentPatchRequest struct for ProjectDocumentPatchRequest
type ProjectDocumentPatchRequest struct {
	ProjectId *string `json:"project_id,omitempty"`
	Slug      *string `json:"slug,omitempty"`
	Title     *string `json:"title,omitempty"`
	Content   *string `json:"content,omitempty"`
}

// NewProjectDocumentPatchRequest instantiates a new ProjectDocumentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectDocumentPatchRequest() *ProjectDocumentPatchRequest {
	this := ProjectDocumentPatchRequest{}
	return &this
}

// NewProjectDocumentPatchRequestWithDefaults instantiates a new ProjectDocumentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectDocumentPatchRequestWithDefaults() *ProjectDocumentPatchRequest {
	this := ProjectDocumentPatchRequest{}
	return &this
}

// GetProjectId returns the ProjectId field value if set, zero value otherwise.
func (o *ProjectDocumentPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDocumentPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

// HasProjectId returns a boolean if a field has been set.
func (o *ProjectDocumentPatchRequest) HasProjectId() bool {
	if o != nil && !IsNil(o.ProjectId) {
		return true
	}

	return false
}

// SetProjectId gets a reference to the given string and assigns it to the ProjectId field.
func (o *ProjectDocumentPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

// GetSlug returns the Slug field value if set, zero value otherwise.
func (o *ProjectDocumentPatchRequest) GetSlug() string {
	if o == nil || IsNil(o.Slug) {
		var ret string
		return ret
	}
	return *o.Slug
}

// GetSlugOk returns a tuple with the Slug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDocumentPatchRequest) GetSlugOk() (*string, bool) {
	if o == nil || IsNil(o.Slug) {
		return nil, false
	}
	return o.Slug, true
}

// HasSlug returns a boolean if a field has been set.
func (o *ProjectDocumentPatchRequest) HasSlug() bool {
	if o != nil && !IsNil(o.Slug) {
		return true
	}

	return false
}

// SetSlug gets a reference to the given string and assigns it to the Slug field.
func (o *ProjectDocumentPatchRequest) SetSlug(v string) {
	o.Slug = &v
}

// GetTitle returns the Title field value if set, zero value otherwise.
func (o *ProjectDocumentPatchRequest) GetTitle() string {
	if o == nil || IsNil(o.Title) {
		var ret string
		return ret
	}
	return *o.Title
}

// GetTitleOk returns a tuple with the Title field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDocumentPatchRequest) GetTitleOk() (*string, bool) {
	if o == nil || IsNil(o.Title) {
		return nil, false
	}
	return o.Title, true
}

// HasTitle returns a boolean if a field has been set.
func (o *ProjectDocumentPatchRequest) HasTitle() bool {
	if o != nil && !IsNil(o.Title) {
		return true
	}

	return false
}

// SetTitle gets a reference to the given string and assigns it to the Title field.
func (o *ProjectDocumentPatchRequest) SetTitle(v string) {
	o.Title = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *ProjectDocumentPatchRequest) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectDocumentPatchRequest) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *ProjectDocumentPatchRequest) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *ProjectDocumentPatchRequest) SetContent(v string) {
	o.Content = &v
}

func (o ProjectDocumentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectDocumentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.Slug) {
		toSerialize["slug"] = o.Slug
	}
	if !IsNil(o.Title) {
		toSerialize["title"] = o.Title
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	return toSerialize, nil
}

type NullableProjectDocumentPatchRequest struct {
	value *ProjectDocumentPatchRequest
	isSet bool
}

func (v NullableProjectDocumentPatchRequest) Get() *ProjectDocumentPatchRequest {
	return v.value
}

func (v *NullableProjectDocumentPatchRequest) Set(val *ProjectDocumentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectDocumentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectDocumentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectDocumentPatchRequest(val *ProjectDocumentPatchRequest) *NullableProjectDocumentPatchRequest {
	return &NullableProjectDocumentPatchRequest{value: val, isSet: true}
}

func (v NullableProjectDocumentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectDocumentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
