/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
	"time"
)

// checks if the ProjectAgent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAgent{}

// ProjectAgent struct for ProjectAgent
type ProjectAgent struct {
	Id        *string    `json:"id,omitempty"`
	Kind      *string    `json:"kind,omitempty"`
	Href      *string    `json:"href,omitempty"`
	CreatedAt *time.Time `json:"created_at,omitempty"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	ProjectId string     `json:"project_id"`
	AgentId   string     `json:"agent_id"`
	// Pinned to a specific Agent version
	AgentVersion *int32 `json:"agent_version,omitempty"`
	// Denormalized for fast reads — the active session, if any
	CurrentSessionId *string `json:"current_session_id,omitempty"`
}

type _ProjectAgent ProjectAgent

// NewProjectAgent instantiates a new ProjectAgent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAgent(projectId string, agentId string) *ProjectAgent {
	this := ProjectAgent{}
	this.ProjectId = projectId
	this.AgentId = agentId
	return &this
}

// NewProjectAgentWithDefaults instantiates a new ProjectAgent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAgentWithDefaults() *ProjectAgent {
	this := ProjectAgent{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ProjectAgent) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ProjectAgent) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *ProjectAgent) SetId(v string) {
	o.Id = &v
}

// GetKind returns the Kind field value if set, zero value otherwise.
func (o *ProjectAgent) GetKind() string {
	if o == nil || IsNil(o.Kind) {
		var ret string
		return ret
	}
	return *o.Kind
}

// GetKindOk returns a tuple with the Kind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetKindOk() (*string, bool) {
	if o == nil || IsNil(o.Kind) {
		return nil, false
	}
	return o.Kind, true
}

// HasKind returns a boolean if a field has been set.
func (o *ProjectAgent) HasKind() bool {
	if o != nil && !IsNil(o.Kind) {
		return true
	}

	return false
}

// SetKind gets a reference to the given string and assigns it to the Kind field.
func (o *ProjectAgent) SetKind(v string) {
	o.Kind = &v
}

// GetHref returns the Href field value if set, zero value otherwise.
func (o *ProjectAgent) GetHref() string {
	if o == nil || IsNil(o.Href) {
		var ret string
		return ret
	}
	return *o.Href
}

// GetHrefOk returns a tuple with the Href field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetHrefOk() (*string, bool) {
	if o == nil || IsNil(o.Href) {
		return nil, false
	}
	return o.Href, true
}

// HasHref returns a boolean if a field has been set.
func (o *ProjectAgent) HasHref() bool {
	if o != nil && !IsNil(o.Href) {
		return true
	}

	return false
}

// SetHref gets a reference to the given string and assigns it to the Href field.
func (o *ProjectAgent) SetHref(v string) {
	o.Href = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ProjectAgent) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ProjectAgent) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ProjectAgent) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *ProjectAgent) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *ProjectAgent) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *ProjectAgent) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetProjectId returns the ProjectId field value
func (o *ProjectAgent) GetProjectId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ProjectId
}

// GetProjectIdOk returns a tuple with the ProjectId field value
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetProjectIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ProjectId, true
}

// SetProjectId sets field value
func (o *ProjectAgent) SetProjectId(v string) {
	o.ProjectId = v
}

// GetAgentId returns the AgentId field value
func (o *ProjectAgent) GetAgentId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetAgentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AgentId, true
}

// SetAgentId sets field value
func (o *ProjectAgent) SetAgentId(v string) {
	o.AgentId = v
}

// GetAgentVersion returns the AgentVersion field value if set, zero value otherwise.
func (o *ProjectAgent) GetAgentVersion() int32 {
	if o == nil || IsNil(o.AgentVersion) {
		var ret int32
		return ret
	}
	return *o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetAgentVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.AgentVersion) {
		return nil, false
	}
	return o.AgentVersion, true
}

// HasAgentVersion returns a boolean if a field has been set.
func (o *ProjectAgent) HasAgentVersion() bool {
	if o != nil && !IsNil(o.AgentVersion) {
		return true
	}

	return false
}

// SetAgentVersion gets a reference to the given int32 and assigns it to the AgentVersion field.
func (o *ProjectAgent) SetAgentVersion(v int32) {
	o.AgentVersion = &v
}

// GetCurrentSessionId returns the CurrentSessionId field value if set, zero value otherwise.
func (o *ProjectAgent) GetCurrentSessionId() string {
	if o == nil || IsNil(o.CurrentSessionId) {
		var ret string
		return ret
	}
	return *o.CurrentSessionId
}

// GetCurrentSessionIdOk returns a tuple with the CurrentSessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgent) GetCurrentSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.CurrentSessionId) {
		return nil, false
	}
	return o.CurrentSessionId, true
}

// HasCurrentSessionId returns a boolean if a field has been set.
func (o *ProjectAgent) HasCurrentSessionId() bool {
	if o != nil && !IsNil(o.CurrentSessionId) {
		return true
	}

	return false
}

// SetCurrentSessionId gets a reference to the given string and assigns it to the CurrentSessionId field.
func (o *ProjectAgent) SetCurrentSessionId(v string) {
	o.CurrentSessionId = &v
}

func (o ProjectAgent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAgent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Kind) {
		toSerialize["kind"] = o.Kind
	}
	if !IsNil(o.Href) {
		toSerialize["href"] = o.Href
	}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated_at"] = o.UpdatedAt
	}
	toSerialize["project_id"] = o.ProjectId
	toSerialize["agent_id"] = o.AgentId
	if !IsNil(o.AgentVersion) {
		toSerialize["agent_version"] = o.AgentVersion
	}
	if !IsNil(o.CurrentSessionId) {
		toSerialize["current_session_id"] = o.CurrentSessionId
	}
	return toSerialize, nil
}

func (o *ProjectAgent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"project_id",
		"agent_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProjectAgent := _ProjectAgent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProjectAgent)

	if err != nil {
		return err
	}

	*o = ProjectAgent(varProjectAgent)

	return err
}

type NullableProjectAgent struct {
	value *ProjectAgent
	isSet bool
}

func (v NullableProjectAgent) Get() *ProjectAgent {
	return v.value
}

func (v *NullableProjectAgent) Set(val *ProjectAgent) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAgent(val *ProjectAgent) *NullableProjectAgent {
	return &NullableProjectAgent{value: val, isSet: true}
}

func (v NullableProjectAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
