/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SessionCheckInPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SessionCheckInPatchRequest{}

// SessionCheckInPatchRequest struct for SessionCheckInPatchRequest
type SessionCheckInPatchRequest struct {
	SessionId *string `json:"session_id,omitempty"`
	AgentId   *string `json:"agent_id,omitempty"`
	Summary   *string `json:"summary,omitempty"`
	Branch    *string `json:"branch,omitempty"`
	Worktree  *string `json:"worktree,omitempty"`
	Pr        *string `json:"pr,omitempty"`
	Phase     *string `json:"phase,omitempty"`
	TestCount *int32  `json:"test_count,omitempty"`
	NextSteps *string `json:"next_steps,omitempty"`
}

// NewSessionCheckInPatchRequest instantiates a new SessionCheckInPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSessionCheckInPatchRequest() *SessionCheckInPatchRequest {
	this := SessionCheckInPatchRequest{}
	return &this
}

// NewSessionCheckInPatchRequestWithDefaults instantiates a new SessionCheckInPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSessionCheckInPatchRequestWithDefaults() *SessionCheckInPatchRequest {
	this := SessionCheckInPatchRequest{}
	return &this
}

// GetSessionId returns the SessionId field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

// GetSessionIdOk returns a tuple with the SessionId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

// HasSessionId returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasSessionId() bool {
	if o != nil && !IsNil(o.SessionId) {
		return true
	}

	return false
}

// SetSessionId gets a reference to the given string and assigns it to the SessionId field.
func (o *SessionCheckInPatchRequest) SetSessionId(v string) {
	o.SessionId = &v
}

// GetAgentId returns the AgentId field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

// GetAgentIdOk returns a tuple with the AgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

// HasAgentId returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasAgentId() bool {
	if o != nil && !IsNil(o.AgentId) {
		return true
	}

	return false
}

// SetAgentId gets a reference to the given string and assigns it to the AgentId field.
func (o *SessionCheckInPatchRequest) SetAgentId(v string) {
	o.AgentId = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *SessionCheckInPatchRequest) SetSummary(v string) {
	o.Summary = &v
}

// GetBranch returns the Branch field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetBranch() string {
	if o == nil || IsNil(o.Branch) {
		var ret string
		return ret
	}
	return *o.Branch
}

// GetBranchOk returns a tuple with the Branch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetBranchOk() (*string, bool) {
	if o == nil || IsNil(o.Branch) {
		return nil, false
	}
	return o.Branch, true
}

// HasBranch returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasBranch() bool {
	if o != nil && !IsNil(o.Branch) {
		return true
	}

	return false
}

// SetBranch gets a reference to the given string and assigns it to the Branch field.
func (o *SessionCheckInPatchRequest) SetBranch(v string) {
	o.Branch = &v
}

// GetWorktree returns the Worktree field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetWorktree() string {
	if o == nil || IsNil(o.Worktree) {
		var ret string
		return ret
	}
	return *o.Worktree
}

// GetWorktreeOk returns a tuple with the Worktree field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetWorktreeOk() (*string, bool) {
	if o == nil || IsNil(o.Worktree) {
		return nil, false
	}
	return o.Worktree, true
}

// HasWorktree returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasWorktree() bool {
	if o != nil && !IsNil(o.Worktree) {
		return true
	}

	return false
}

// SetWorktree gets a reference to the given string and assigns it to the Worktree field.
func (o *SessionCheckInPatchRequest) SetWorktree(v string) {
	o.Worktree = &v
}

// GetPr returns the Pr field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetPr() string {
	if o == nil || IsNil(o.Pr) {
		var ret string
		return ret
	}
	return *o.Pr
}

// GetPrOk returns a tuple with the Pr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetPrOk() (*string, bool) {
	if o == nil || IsNil(o.Pr) {
		return nil, false
	}
	return o.Pr, true
}

// HasPr returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasPr() bool {
	if o != nil && !IsNil(o.Pr) {
		return true
	}

	return false
}

// SetPr gets a reference to the given string and assigns it to the Pr field.
func (o *SessionCheckInPatchRequest) SetPr(v string) {
	o.Pr = &v
}

// GetPhase returns the Phase field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetPhase() string {
	if o == nil || IsNil(o.Phase) {
		var ret string
		return ret
	}
	return *o.Phase
}

// GetPhaseOk returns a tuple with the Phase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.Phase) {
		return nil, false
	}
	return o.Phase, true
}

// HasPhase returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasPhase() bool {
	if o != nil && !IsNil(o.Phase) {
		return true
	}

	return false
}

// SetPhase gets a reference to the given string and assigns it to the Phase field.
func (o *SessionCheckInPatchRequest) SetPhase(v string) {
	o.Phase = &v
}

// GetTestCount returns the TestCount field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetTestCount() int32 {
	if o == nil || IsNil(o.TestCount) {
		var ret int32
		return ret
	}
	return *o.TestCount
}

// GetTestCountOk returns a tuple with the TestCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetTestCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TestCount) {
		return nil, false
	}
	return o.TestCount, true
}

// HasTestCount returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasTestCount() bool {
	if o != nil && !IsNil(o.TestCount) {
		return true
	}

	return false
}

// SetTestCount gets a reference to the given int32 and assigns it to the TestCount field.
func (o *SessionCheckInPatchRequest) SetTestCount(v int32) {
	o.TestCount = &v
}

// GetNextSteps returns the NextSteps field value if set, zero value otherwise.
func (o *SessionCheckInPatchRequest) GetNextSteps() string {
	if o == nil || IsNil(o.NextSteps) {
		var ret string
		return ret
	}
	return *o.NextSteps
}

// GetNextStepsOk returns a tuple with the NextSteps field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SessionCheckInPatchRequest) GetNextStepsOk() (*string, bool) {
	if o == nil || IsNil(o.NextSteps) {
		return nil, false
	}
	return o.NextSteps, true
}

// HasNextSteps returns a boolean if a field has been set.
func (o *SessionCheckInPatchRequest) HasNextSteps() bool {
	if o != nil && !IsNil(o.NextSteps) {
		return true
	}

	return false
}

// SetNextSteps gets a reference to the given string and assigns it to the NextSteps field.
func (o *SessionCheckInPatchRequest) SetNextSteps(v string) {
	o.NextSteps = &v
}

func (o SessionCheckInPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SessionCheckInPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.SessionId) {
		toSerialize["session_id"] = o.SessionId
	}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	if !IsNil(o.Branch) {
		toSerialize["branch"] = o.Branch
	}
	if !IsNil(o.Worktree) {
		toSerialize["worktree"] = o.Worktree
	}
	if !IsNil(o.Pr) {
		toSerialize["pr"] = o.Pr
	}
	if !IsNil(o.Phase) {
		toSerialize["phase"] = o.Phase
	}
	if !IsNil(o.TestCount) {
		toSerialize["test_count"] = o.TestCount
	}
	if !IsNil(o.NextSteps) {
		toSerialize["next_steps"] = o.NextSteps
	}
	return toSerialize, nil
}

type NullableSessionCheckInPatchRequest struct {
	value *SessionCheckInPatchRequest
	isSet bool
}

func (v NullableSessionCheckInPatchRequest) Get() *SessionCheckInPatchRequest {
	return v.value
}

func (v *NullableSessionCheckInPatchRequest) Set(val *SessionCheckInPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSessionCheckInPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSessionCheckInPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSessionCheckInPatchRequest(val *SessionCheckInPatchRequest) *NullableSessionCheckInPatchRequest {
	return &NullableSessionCheckInPatchRequest{value: val, isSet: true}
}

func (v NullableSessionCheckInPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSessionCheckInPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
