/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectAgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAgentPatchRequest{}

// ProjectAgentPatchRequest struct for ProjectAgentPatchRequest
type ProjectAgentPatchRequest struct {
	// Re-pin this ProjectAgent to a different Agent version
	AgentVersion *int32 `json:"agent_version,omitempty"`
}

// NewProjectAgentPatchRequest instantiates a new ProjectAgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAgentPatchRequest() *ProjectAgentPatchRequest {
	this := ProjectAgentPatchRequest{}
	return &this
}

// NewProjectAgentPatchRequestWithDefaults instantiates a new ProjectAgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAgentPatchRequestWithDefaults() *ProjectAgentPatchRequest {
	this := ProjectAgentPatchRequest{}
	return &this
}

// GetAgentVersion returns the AgentVersion field value if set, zero value otherwise.
func (o *ProjectAgentPatchRequest) GetAgentVersion() int32 {
	if o == nil || IsNil(o.AgentVersion) {
		var ret int32
		return ret
	}
	return *o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgentPatchRequest) GetAgentVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.AgentVersion) {
		return nil, false
	}
	return o.AgentVersion, true
}

// HasAgentVersion returns a boolean if a field has been set.
func (o *ProjectAgentPatchRequest) HasAgentVersion() bool {
	if o != nil && !IsNil(o.AgentVersion) {
		return true
	}

	return false
}

// SetAgentVersion gets a reference to the given int32 and assigns it to the AgentVersion field.
func (o *ProjectAgentPatchRequest) SetAgentVersion(v int32) {
	o.AgentVersion = &v
}

func (o ProjectAgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AgentVersion) {
		toSerialize["agent_version"] = o.AgentVersion
	}
	return toSerialize, nil
}

type NullableProjectAgentPatchRequest struct {
	value *ProjectAgentPatchRequest
	isSet bool
}

func (v NullableProjectAgentPatchRequest) Get() *ProjectAgentPatchRequest {
	return v.value
}

func (v *NullableProjectAgentPatchRequest) Set(val *ProjectAgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAgentPatchRequest(val *ProjectAgentPatchRequest) *NullableProjectAgentPatchRequest {
	return &NullableProjectAgentPatchRequest{value: val, isSet: true}
}

func (v NullableProjectAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
