/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectAgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectAgentPatchRequest{}

// ProjectAgentPatchRequest struct for ProjectAgentPatchRequest
type ProjectAgentPatchRequest struct {
	Name *string `json:"name,omitempty"`
	// Update agent prompt (access controlled by RBAC)
	Prompt      *string `json:"prompt,omitempty"`
	Labels      *string `json:"labels,omitempty"`
	Annotations *string `json:"annotations,omitempty"`
}

// NewProjectAgentPatchRequest instantiates a new ProjectAgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectAgentPatchRequest() *ProjectAgentPatchRequest {
	this := ProjectAgentPatchRequest{}
	return &this
}

// NewProjectAgentPatchRequestWithDefaults instantiates a new ProjectAgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectAgentPatchRequestWithDefaults() *ProjectAgentPatchRequest {
	this := ProjectAgentPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ProjectAgentPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgentPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ProjectAgentPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ProjectAgentPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *ProjectAgentPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgentPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *ProjectAgentPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *ProjectAgentPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *ProjectAgentPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgentPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *ProjectAgentPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *ProjectAgentPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *ProjectAgentPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectAgentPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *ProjectAgentPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *ProjectAgentPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

func (o ProjectAgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectAgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

type NullableProjectAgentPatchRequest struct {
	value *ProjectAgentPatchRequest
	isSet bool
}

func (v NullableProjectAgentPatchRequest) Get() *ProjectAgentPatchRequest {
	return v.value
}

func (v *NullableProjectAgentPatchRequest) Set(val *ProjectAgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectAgentPatchRequest(val *ProjectAgentPatchRequest) *NullableProjectAgentPatchRequest {
	return &NullableProjectAgentPatchRequest{value: val, isSet: true}
}

func (v NullableProjectAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
