/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentPatchRequest{}

// AgentPatchRequest PATCH creates a new Agent version (version+1). The prior version is preserved.
type AgentPatchRequest struct {
	// Updating prompt creates a new immutable version of this agent
	Prompt *string `json:"prompt,omitempty"`
}

// NewAgentPatchRequest instantiates a new AgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentPatchRequest() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// NewAgentPatchRequestWithDefaults instantiates a new AgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentPatchRequestWithDefaults() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *AgentPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

func (o AgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	return toSerialize, nil
}

type NullableAgentPatchRequest struct {
	value *AgentPatchRequest
	isSet bool
}

func (v NullableAgentPatchRequest) Get() *AgentPatchRequest {
	return v.value
}

func (v *NullableAgentPatchRequest) Set(val *AgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPatchRequest(val *AgentPatchRequest) *NullableAgentPatchRequest {
	return &NullableAgentPatchRequest{value: val, isSet: true}
}

func (v NullableAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
