/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the IgniteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IgniteResponse{}

// IgniteResponse struct for IgniteResponse
type IgniteResponse struct {
	Session *Session `json:"session,omitempty"`
	// Assembled ignition context — Project.prompt + Agent.prompt + Inbox + Session.prompt + peer roster
	IgnitionContext *string `json:"ignition_context,omitempty"`
}

// NewIgniteResponse instantiates a new IgniteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIgniteResponse() *IgniteResponse {
	this := IgniteResponse{}
	return &this
}

// NewIgniteResponseWithDefaults instantiates a new IgniteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIgniteResponseWithDefaults() *IgniteResponse {
	this := IgniteResponse{}
	return &this
}

// GetSession returns the Session field value if set, zero value otherwise.
func (o *IgniteResponse) GetSession() Session {
	if o == nil || IsNil(o.Session) {
		var ret Session
		return ret
	}
	return *o.Session
}

// GetSessionOk returns a tuple with the Session field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgniteResponse) GetSessionOk() (*Session, bool) {
	if o == nil || IsNil(o.Session) {
		return nil, false
	}
	return o.Session, true
}

// HasSession returns a boolean if a field has been set.
func (o *IgniteResponse) HasSession() bool {
	if o != nil && !IsNil(o.Session) {
		return true
	}

	return false
}

// SetSession gets a reference to the given Session and assigns it to the Session field.
func (o *IgniteResponse) SetSession(v Session) {
	o.Session = &v
}

// GetIgnitionContext returns the IgnitionContext field value if set, zero value otherwise.
func (o *IgniteResponse) GetIgnitionContext() string {
	if o == nil || IsNil(o.IgnitionContext) {
		var ret string
		return ret
	}
	return *o.IgnitionContext
}

// GetIgnitionContextOk returns a tuple with the IgnitionContext field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IgniteResponse) GetIgnitionContextOk() (*string, bool) {
	if o == nil || IsNil(o.IgnitionContext) {
		return nil, false
	}
	return o.IgnitionContext, true
}

// HasIgnitionContext returns a boolean if a field has been set.
func (o *IgniteResponse) HasIgnitionContext() bool {
	if o != nil && !IsNil(o.IgnitionContext) {
		return true
	}

	return false
}

// SetIgnitionContext gets a reference to the given string and assigns it to the IgnitionContext field.
func (o *IgniteResponse) SetIgnitionContext(v string) {
	o.IgnitionContext = &v
}

func (o IgniteResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IgniteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Session) {
		toSerialize["session"] = o.Session
	}
	if !IsNil(o.IgnitionContext) {
		toSerialize["ignition_context"] = o.IgnitionContext
	}
	return toSerialize, nil
}

type NullableIgniteResponse struct {
	value *IgniteResponse
	isSet bool
}

func (v NullableIgniteResponse) Get() *IgniteResponse {
	return v.value
}

func (v *NullableIgniteResponse) Set(val *IgniteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIgniteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIgniteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIgniteResponse(val *IgniteResponse) *NullableIgniteResponse {
	return &NullableIgniteResponse{value: val, isSet: true}
}

func (v NullableIgniteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIgniteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
