/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProjectHomeAgent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProjectHomeAgent{}

// ProjectHomeAgent struct for ProjectHomeAgent
type ProjectHomeAgent struct {
	ProjectAgentId   *string `json:"project_agent_id,omitempty"`
	AgentName        *string `json:"agent_name,omitempty"`
	AgentVersion     *int32  `json:"agent_version,omitempty"`
	SessionPhase     *string `json:"session_phase,omitempty"`
	InboxUnreadCount *int32  `json:"inbox_unread_count,omitempty"`
	Summary          *string `json:"summary,omitempty"`
}

// NewProjectHomeAgent instantiates a new ProjectHomeAgent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProjectHomeAgent() *ProjectHomeAgent {
	this := ProjectHomeAgent{}
	return &this
}

// NewProjectHomeAgentWithDefaults instantiates a new ProjectHomeAgent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProjectHomeAgentWithDefaults() *ProjectHomeAgent {
	this := ProjectHomeAgent{}
	return &this
}

// GetProjectAgentId returns the ProjectAgentId field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetProjectAgentId() string {
	if o == nil || IsNil(o.ProjectAgentId) {
		var ret string
		return ret
	}
	return *o.ProjectAgentId
}

// GetProjectAgentIdOk returns a tuple with the ProjectAgentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetProjectAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectAgentId) {
		return nil, false
	}
	return o.ProjectAgentId, true
}

// HasProjectAgentId returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasProjectAgentId() bool {
	if o != nil && !IsNil(o.ProjectAgentId) {
		return true
	}

	return false
}

// SetProjectAgentId gets a reference to the given string and assigns it to the ProjectAgentId field.
func (o *ProjectHomeAgent) SetProjectAgentId(v string) {
	o.ProjectAgentId = &v
}

// GetAgentName returns the AgentName field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetAgentName() string {
	if o == nil || IsNil(o.AgentName) {
		var ret string
		return ret
	}
	return *o.AgentName
}

// GetAgentNameOk returns a tuple with the AgentName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetAgentNameOk() (*string, bool) {
	if o == nil || IsNil(o.AgentName) {
		return nil, false
	}
	return o.AgentName, true
}

// HasAgentName returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasAgentName() bool {
	if o != nil && !IsNil(o.AgentName) {
		return true
	}

	return false
}

// SetAgentName gets a reference to the given string and assigns it to the AgentName field.
func (o *ProjectHomeAgent) SetAgentName(v string) {
	o.AgentName = &v
}

// GetAgentVersion returns the AgentVersion field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetAgentVersion() int32 {
	if o == nil || IsNil(o.AgentVersion) {
		var ret int32
		return ret
	}
	return *o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetAgentVersionOk() (*int32, bool) {
	if o == nil || IsNil(o.AgentVersion) {
		return nil, false
	}
	return o.AgentVersion, true
}

// HasAgentVersion returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasAgentVersion() bool {
	if o != nil && !IsNil(o.AgentVersion) {
		return true
	}

	return false
}

// SetAgentVersion gets a reference to the given int32 and assigns it to the AgentVersion field.
func (o *ProjectHomeAgent) SetAgentVersion(v int32) {
	o.AgentVersion = &v
}

// GetSessionPhase returns the SessionPhase field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetSessionPhase() string {
	if o == nil || IsNil(o.SessionPhase) {
		var ret string
		return ret
	}
	return *o.SessionPhase
}

// GetSessionPhaseOk returns a tuple with the SessionPhase field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetSessionPhaseOk() (*string, bool) {
	if o == nil || IsNil(o.SessionPhase) {
		return nil, false
	}
	return o.SessionPhase, true
}

// HasSessionPhase returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasSessionPhase() bool {
	if o != nil && !IsNil(o.SessionPhase) {
		return true
	}

	return false
}

// SetSessionPhase gets a reference to the given string and assigns it to the SessionPhase field.
func (o *ProjectHomeAgent) SetSessionPhase(v string) {
	o.SessionPhase = &v
}

// GetInboxUnreadCount returns the InboxUnreadCount field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetInboxUnreadCount() int32 {
	if o == nil || IsNil(o.InboxUnreadCount) {
		var ret int32
		return ret
	}
	return *o.InboxUnreadCount
}

// GetInboxUnreadCountOk returns a tuple with the InboxUnreadCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetInboxUnreadCountOk() (*int32, bool) {
	if o == nil || IsNil(o.InboxUnreadCount) {
		return nil, false
	}
	return o.InboxUnreadCount, true
}

// HasInboxUnreadCount returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasInboxUnreadCount() bool {
	if o != nil && !IsNil(o.InboxUnreadCount) {
		return true
	}

	return false
}

// SetInboxUnreadCount gets a reference to the given int32 and assigns it to the InboxUnreadCount field.
func (o *ProjectHomeAgent) SetInboxUnreadCount(v int32) {
	o.InboxUnreadCount = &v
}

// GetSummary returns the Summary field value if set, zero value otherwise.
func (o *ProjectHomeAgent) GetSummary() string {
	if o == nil || IsNil(o.Summary) {
		var ret string
		return ret
	}
	return *o.Summary
}

// GetSummaryOk returns a tuple with the Summary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProjectHomeAgent) GetSummaryOk() (*string, bool) {
	if o == nil || IsNil(o.Summary) {
		return nil, false
	}
	return o.Summary, true
}

// HasSummary returns a boolean if a field has been set.
func (o *ProjectHomeAgent) HasSummary() bool {
	if o != nil && !IsNil(o.Summary) {
		return true
	}

	return false
}

// SetSummary gets a reference to the given string and assigns it to the Summary field.
func (o *ProjectHomeAgent) SetSummary(v string) {
	o.Summary = &v
}

func (o ProjectHomeAgent) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProjectHomeAgent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ProjectAgentId) {
		toSerialize["project_agent_id"] = o.ProjectAgentId
	}
	if !IsNil(o.AgentName) {
		toSerialize["agent_name"] = o.AgentName
	}
	if !IsNil(o.AgentVersion) {
		toSerialize["agent_version"] = o.AgentVersion
	}
	if !IsNil(o.SessionPhase) {
		toSerialize["session_phase"] = o.SessionPhase
	}
	if !IsNil(o.InboxUnreadCount) {
		toSerialize["inbox_unread_count"] = o.InboxUnreadCount
	}
	if !IsNil(o.Summary) {
		toSerialize["summary"] = o.Summary
	}
	return toSerialize, nil
}

type NullableProjectHomeAgent struct {
	value *ProjectHomeAgent
	isSet bool
}

func (v NullableProjectHomeAgent) Get() *ProjectHomeAgent {
	return v.value
}

func (v *NullableProjectHomeAgent) Set(val *ProjectHomeAgent) {
	v.value = val
	v.isSet = true
}

func (v NullableProjectHomeAgent) IsSet() bool {
	return v.isSet
}

func (v *NullableProjectHomeAgent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProjectHomeAgent(val *ProjectHomeAgent) *NullableProjectHomeAgent {
	return &NullableProjectHomeAgent{value: val, isSet: true}
}

func (v NullableProjectHomeAgent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProjectHomeAgent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
