/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the AgentMessageList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentMessageList{}

// AgentMessageList struct for AgentMessageList
type AgentMessageList struct {
	Kind  string         `json:"kind"`
	Page  int32          `json:"page"`
	Size  int32          `json:"size"`
	Total int32          `json:"total"`
	Items []AgentMessage `json:"items"`
}

type _AgentMessageList AgentMessageList

// NewAgentMessageList instantiates a new AgentMessageList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentMessageList(kind string, page int32, size int32, total int32, items []AgentMessage) *AgentMessageList {
	this := AgentMessageList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewAgentMessageListWithDefaults instantiates a new AgentMessageList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentMessageListWithDefaults() *AgentMessageList {
	this := AgentMessageList{}
	return &this
}

// GetKind returns the Kind field value
func (o *AgentMessageList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *AgentMessageList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *AgentMessageList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *AgentMessageList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *AgentMessageList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *AgentMessageList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *AgentMessageList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *AgentMessageList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *AgentMessageList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *AgentMessageList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *AgentMessageList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *AgentMessageList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *AgentMessageList) GetItems() []AgentMessage {
	if o == nil {
		var ret []AgentMessage
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *AgentMessageList) GetItemsOk() ([]AgentMessage, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *AgentMessageList) SetItems(v []AgentMessage) {
	o.Items = v
}

func (o AgentMessageList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentMessageList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *AgentMessageList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAgentMessageList := _AgentMessageList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAgentMessageList)

	if err != nil {
		return err
	}

	*o = AgentMessageList(varAgentMessageList)

	return err
}

type NullableAgentMessageList struct {
	value *AgentMessageList
	isSet bool
}

func (v NullableAgentMessageList) Get() *AgentMessageList {
	return v.value
}

func (v *NullableAgentMessageList) Set(val *AgentMessageList) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentMessageList) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentMessageList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentMessageList(val *AgentMessageList) *NullableAgentMessageList {
	return &NullableAgentMessageList{value: val, isSet: true}
}

func (v NullableAgentMessageList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentMessageList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
