// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { AGUIEvent, AGUIEventList, AGUIEventCreateRequest, AGUIEventPatchRequest } from './a_g_u_i_event';

export class AGUIEventAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: AGUIEventCreateRequest, opts?: RequestOptions): Promise<AGUIEvent> {
    return ambientFetch<AGUIEvent>(this.config, 'POST', '/ag_ui_events', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<AGUIEvent> {
    return ambientFetch<AGUIEvent>(this.config, 'GET', `/ag_ui_events/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<AGUIEventList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AGUIEventList>(this.config, 'GET', `/ag_ui_events${qs}`, undefined, opts);
  }
  async update(id: string, patch: AGUIEventPatchRequest, opts?: RequestOptions): Promise<AGUIEvent> {
    return ambientFetch<AGUIEvent>(this.config, 'PATCH', `/ag_ui_events/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<AGUIEvent> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
