// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

import type { ObjectReference, ListMeta } from './base';

export type AGUIEvent = ObjectReference & {
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type AGUIEventList = ListMeta & {
  items: AGUIEvent[];
};

export type AGUIEventCreateRequest = {
  event_type: string;
  payload?: string;
  seq?: number;
  session_id: string;
};

export type AGUIEventPatchRequest = {
  event_type?: string;
  payload?: string;
  seq?: number;
  session_id?: string;
};

export class AGUIEventBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  seq(value: number): this {
    this.data['seq'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  build(): AGUIEventCreateRequest {
    if (!this.data['event_type']) {
      throw new Error('event_type is required');
    }
    if (!this.data['session_id']) {
      throw new Error('session_id is required');
    }
    return this.data as AGUIEventCreateRequest;
  }
}

export class AGUIEventPatchBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  seq(value: number): this {
    this.data['seq'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  build(): AGUIEventPatchRequest {
    return this.data as AGUIEventPatchRequest;
  }
}
