// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { AgentMessage, AgentMessageList, AgentMessageCreateRequest, AgentMessagePatchRequest } from './agent_message';

export class AgentMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: AgentMessageCreateRequest, opts?: RequestOptions): Promise<AgentMessage> {
    return ambientFetch<AgentMessage>(this.config, 'POST', '/agent_messages', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<AgentMessage> {
    return ambientFetch<AgentMessage>(this.config, 'GET', `/agent_messages/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentMessageList>(this.config, 'GET', `/agent_messages${qs}`, undefined, opts);
  }
  async update(id: string, patch: AgentMessagePatchRequest, opts?: RequestOptions): Promise<AgentMessage> {
    return ambientFetch<AgentMessage>(this.config, 'PATCH', `/agent_messages/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<AgentMessage> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
