// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { ObjectReference, ListMeta } from './base';

export type AgentMessage = ObjectReference & {
  body: string;
  read: boolean;
  recipient_agent_id: string;
  sender_agent_id: string;
  sender_name: string;
  sender_user_id: string;
};

export type AgentMessageList = ListMeta & {
  items: AgentMessage[];
};

export type AgentMessageCreateRequest = {
  body?: string;
  read?: boolean;
  recipient_agent_id: string;
  sender_agent_id?: string;
  sender_name?: string;
  sender_user_id?: string;
};

export type AgentMessagePatchRequest = {
  body?: string;
  read?: boolean;
  recipient_agent_id?: string;
  sender_agent_id?: string;
  sender_name?: string;
  sender_user_id?: string;
};

export class AgentMessageBuilder {
  private data: Record<string, unknown> = {};


  body(value: string): this {
    this.data['body'] = value;
    return this;
  }

  read(value: boolean): this {
    this.data['read'] = value;
    return this;
  }

  recipientAgentId(value: string): this {
    this.data['recipient_agent_id'] = value;
    return this;
  }

  senderAgentId(value: string): this {
    this.data['sender_agent_id'] = value;
    return this;
  }

  senderName(value: string): this {
    this.data['sender_name'] = value;
    return this;
  }

  senderUserId(value: string): this {
    this.data['sender_user_id'] = value;
    return this;
  }

  build(): AgentMessageCreateRequest {
    if (!this.data['recipient_agent_id']) {
      throw new Error('recipient_agent_id is required');
    }
    return this.data as AgentMessageCreateRequest;
  }
}

export class AgentMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  body(value: string): this {
    this.data['body'] = value;
    return this;
  }

  read(value: boolean): this {
    this.data['read'] = value;
    return this;
  }

  recipientAgentId(value: string): this {
    this.data['recipient_agent_id'] = value;
    return this;
  }

  senderAgentId(value: string): this {
    this.data['sender_agent_id'] = value;
    return this;
  }

  senderName(value: string): this {
    this.data['sender_name'] = value;
    return this;
  }

  senderUserId(value: string): this {
    this.data['sender_user_id'] = value;
    return this;
  }

  build(): AgentMessagePatchRequest {
    return this.data as AgentMessagePatchRequest;
  }
}

