// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 6aa380e2811c748da7e24b50bed0ae9908aed8cd7f7760fe274776b84726faf2
// Generated: 2026-04-24T08:29:20Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Agent, AgentList, AgentCreateRequest, AgentPatchRequest } from './agent';

export class AgentAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    return '/projects/{id}/agents'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: AgentCreateRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: AgentPatchRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async start(id: string, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'POST', `${this.basePath()}/${id}/start`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Agent> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
