// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 27ef174cf2467464266e7bfc9d0aa30984a2ad917d93fdaded13f563c44af739
// Generated: 2026-02-24T23:06:46Z

import type { AmbientClientConfig } from './base';
import { ProjectAPI } from './project_api';
import { ProjectSettingsAPI } from './project_settings_api';
import { SessionAPI } from './session_api';
import { UserAPI } from './user_api';


export class AmbientClient {
  private readonly config: AmbientClientConfig;

  readonly projects: ProjectAPI;
  readonly projectSettings: ProjectSettingsAPI;
  readonly sessions: SessionAPI;
  readonly users: UserAPI;

  constructor(config: AmbientClientConfig) {
    if (!config.baseUrl) {
      throw new Error('baseUrl is required');
    }
    if (!config.token) {
      throw new Error('token is required');
    }
    if (!config.project) {
      throw new Error('project is required');
    }

    this.config = {
      ...config,
      baseUrl: config.baseUrl.replace(/\/+$/, ''),
    };

    this.projects = new ProjectAPI(this.config);
    this.projectSettings = new ProjectSettingsAPI(this.config);
    this.sessions = new SessionAPI(this.config);
    this.users = new UserAPI(this.config);
  }

  static fromEnv(): AmbientClient {
    const baseUrl = process.env.AMBIENT_API_URL || 'http://localhost:8080';
    const token = process.env.AMBIENT_TOKEN;
    const project = process.env.AMBIENT_PROJECT;

    if (!token) {
      throw new Error('AMBIENT_TOKEN environment variable is required');
    }
    if (!project) {
      throw new Error('AMBIENT_PROJECT environment variable is required');
    }

    return new AmbientClient({ baseUrl, token, project });
  }
}
