// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z

import type { ObjectReference, ListMeta } from './base';

export type InboxMessage = ObjectReference & {
  body: string;
  from_name: string;
  from_project_agent_id: string;
  project_agent_id: string;
  read: boolean;
};

export type InboxMessageList = ListMeta & {
  items: InboxMessage[];
};

export type InboxMessageCreateRequest = {
  body: string;
  from_name?: string;
  from_project_agent_id?: string;
  project_agent_id: string;
};

export type InboxMessagePatchRequest = {
  read?: boolean;
};

export class InboxMessageBuilder {
  private data: Record<string, unknown> = {};


  body(value: string): this {
    this.data['body'] = value;
    return this;
  }

  fromName(value: string): this {
    this.data['from_name'] = value;
    return this;
  }

  fromProjectAgentId(value: string): this {
    this.data['from_project_agent_id'] = value;
    return this;
  }

  projectAgentId(value: string): this {
    this.data['project_agent_id'] = value;
    return this;
  }

  build(): InboxMessageCreateRequest {
    if (!this.data['body']) {
      throw new Error('body is required');
    }
    if (!this.data['project_agent_id']) {
      throw new Error('project_agent_id is required');
    }
    return this.data as InboxMessageCreateRequest;
  }
}

export class InboxMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  read(value: boolean): this {
    this.data['read'] = value;
    return this;
  }

  build(): InboxMessagePatchRequest {
    return this.data as InboxMessagePatchRequest;
  }
}
