// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { InboxMessage, InboxMessageList, InboxMessageCreateRequest } from './inbox_message';

export class InboxMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async send(projectId: string, paId: string, data: InboxMessageCreateRequest, opts?: RequestOptions): Promise<InboxMessage> {
    return ambientFetch<InboxMessage>(this.config, 'POST', `/projects/${projectId}/agents/${paId}/inbox`, data, opts);
  }

  async list(projectId: string, paId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<InboxMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<InboxMessageList>(this.config, 'GET', `/projects/${projectId}/agents/${paId}/inbox${qs}`, undefined, opts);
  }

  async *listAll(projectId: string, paId: string, size: number = 100, opts?: RequestOptions): AsyncGenerator<InboxMessage> {
    let page = 1;
    while (true) {
      const result = await this.list(projectId, paId, { page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }

  async markRead(projectId: string, paId: string, msgId: string, opts?: RequestOptions): Promise<InboxMessage> {
    return ambientFetch<InboxMessage>(this.config, 'PATCH', `/projects/${projectId}/agents/${paId}/inbox/${msgId}`, { read: true }, opts);
  }

  async delete(projectId: string, paId: string, msgId: string, opts?: RequestOptions): Promise<void> {
    await ambientFetch<void>(this.config, 'DELETE', `/projects/${projectId}/agents/${paId}/inbox/${msgId}`, undefined, opts);
  }
}
