// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectAgent = ObjectReference & {
  agent_id: string;
  agent_version: number;
  current_session_id: string;
  project_id: string;
};

export type ProjectAgentList = ListMeta & {
  items: ProjectAgent[];
};

export type ProjectAgentCreateRequest = {
  agent_id: string;
  agent_version?: number;
  project_id: string;
};

export type ProjectAgentPatchRequest = {
  agent_version?: number;
};

export class ProjectAgentBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  agentVersion(value: number): this {
    this.data['agent_version'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  build(): ProjectAgentCreateRequest {
    if (!this.data['agent_id']) {
      throw new Error('agent_id is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProjectAgentCreateRequest;
  }
}

export class ProjectAgentPatchBuilder {
  private data: Record<string, unknown> = {};


  agentVersion(value: number): this {
    this.data['agent_version'] = value;
    return this;
  }

  build(): ProjectAgentPatchRequest {
    return this.data as ProjectAgentPatchRequest;
  }
}
