// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f0ec84178602f3437cc365a1e354b5286dbd72ff5c138db499664f62b927bb61
// Generated: 2026-02-28T15:30:52Z

import type { ObjectReference, ListMeta } from './base';

export type Project = ObjectReference & {
  annotations: string;
  description: string;
  display_name: string;
  labels: string;
  name: string;
  status: string;
};

export type ProjectList = ListMeta & {
  items: Project[];
};

export type ProjectCreateRequest = {
  annotations?: string;
  description?: string;
  display_name?: string;
  labels?: string;
  name: string;
  status?: string;
};

export type ProjectPatchRequest = {
  annotations?: string;
  description?: string;
  display_name?: string;
  labels?: string;
  name?: string;
  status?: string;
};

export class ProjectBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as ProjectCreateRequest;
  }
}

export class ProjectPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectPatchRequest {
    return this.data as ProjectPatchRequest;
  }
}

