// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { ProjectAgent, ProjectAgentList, ProjectAgentCreateRequest, ProjectAgentPatchRequest } from './project_agent';
import type { Session, SessionList } from './session';

export type IgniteRequest = {
  prompt?: string;
};

export type IgniteResponse = {
  session?: Session;
  ignition_context?: string;
};

export class ProjectAgentAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(projectId: string, data: ProjectAgentCreateRequest, opts?: RequestOptions): Promise<ProjectAgent> {
    return ambientFetch<ProjectAgent>(this.config, 'POST', `/projects/${projectId}/agents`, data, opts);
  }

  async get(projectId: string, paId: string, opts?: RequestOptions): Promise<ProjectAgent> {
    return ambientFetch<ProjectAgent>(this.config, 'GET', `/projects/${projectId}/agents/${paId}`, undefined, opts);
  }

  async list(projectId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<ProjectAgentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ProjectAgentList>(this.config, 'GET', `/projects/${projectId}/agents${qs}`, undefined, opts);
  }

  async *listAll(projectId: string, size: number = 100, opts?: RequestOptions): AsyncGenerator<ProjectAgent> {
    let page = 1;
    while (true) {
      const result = await this.list(projectId, { page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }

  async update(projectId: string, paId: string, patch: ProjectAgentPatchRequest, opts?: RequestOptions): Promise<ProjectAgent> {
    return ambientFetch<ProjectAgent>(this.config, 'PATCH', `/projects/${projectId}/agents/${paId}`, patch, opts);
  }

  async delete(projectId: string, paId: string, opts?: RequestOptions): Promise<void> {
    await ambientFetch<void>(this.config, 'DELETE', `/projects/${projectId}/agents/${paId}`, undefined, opts);
  }

  async ignite(projectId: string, paId: string, prompt?: string, opts?: RequestOptions): Promise<IgniteResponse> {
    const body: IgniteRequest = prompt ? { prompt } : {};
    return ambientFetch<IgniteResponse>(this.config, 'POST', `/projects/${projectId}/agents/${paId}/ignite`, body, opts);
  }

  async getIgnition(projectId: string, paId: string, opts?: RequestOptions): Promise<IgniteResponse> {
    return ambientFetch<IgniteResponse>(this.config, 'GET', `/projects/${projectId}/agents/${paId}/ignition`, undefined, opts);
  }

  async sessions(projectId: string, paId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionList>(this.config, 'GET', `/projects/${projectId}/agents/${paId}/sessions${qs}`, undefined, opts);
  }
}
