// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f0ec84178602f3437cc365a1e354b5286dbd72ff5c138db499664f62b927bb61
// Generated: 2026-02-28T02:20:09Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { ProjectSettings, ProjectSettingsList, ProjectSettingsCreateRequest } from './project_settings';

export class ProjectSettingsAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ProjectSettingsCreateRequest, opts?: RequestOptions): Promise<ProjectSettings> {
    return ambientFetch<ProjectSettings>(this.config, 'POST', '/project_settings', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ProjectSettings> {
    return ambientFetch<ProjectSettings>(this.config, 'GET', `/project_settings/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ProjectSettingsList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ProjectSettingsList>(this.config, 'GET', `/project_settings${qs}`, undefined, opts);
  }
  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ProjectSettings> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
