// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectDocument = ObjectReference & {
  content: string;
  project_id: string;
  slug: string;
  title: string;
};

export type ProjectDocumentList = ListMeta & {
  items: ProjectDocument[];
};

export type ProjectDocumentCreateRequest = {
  content?: string;
  project_id: string;
  slug: string;
  title?: string;
};

export type ProjectDocumentPatchRequest = {
  content?: string;
  project_id?: string;
  slug?: string;
  title?: string;
};

export class ProjectDocumentBuilder {
  private data: Record<string, unknown> = {};


  content(value: string): this {
    this.data['content'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  slug(value: string): this {
    this.data['slug'] = value;
    return this;
  }

  title(value: string): this {
    this.data['title'] = value;
    return this;
  }

  build(): ProjectDocumentCreateRequest {
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    if (!this.data['slug']) {
      throw new Error('slug is required');
    }
    return this.data as ProjectDocumentCreateRequest;
  }
}

export class ProjectDocumentPatchBuilder {
  private data: Record<string, unknown> = {};


  content(value: string): this {
    this.data['content'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  slug(value: string): this {
    this.data['slug'] = value;
    return this;
  }

  title(value: string): this {
    this.data['title'] = value;
    return this;
  }

  build(): ProjectDocumentPatchRequest {
    return this.data as ProjectDocumentPatchRequest;
  }
}

