// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectAgent = ObjectReference & {
  annotations: string;
  current_session_id: string;
  labels: string;
  name: string;
  project_id: string;
  prompt: string;
};

export type ProjectAgentList = ListMeta & {
  items: ProjectAgent[];
};

export type ProjectAgentCreateRequest = {
  annotations?: string;
  labels?: string;
  name: string;
  project_id: string;
  prompt?: string;
};

export type ProjectAgentPatchRequest = {
  annotations?: string;
  labels?: string;
  name?: string;
  prompt?: string;
};

export class ProjectAgentBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  build(): ProjectAgentCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProjectAgentCreateRequest;
  }
}

export class ProjectAgentPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  build(): ProjectAgentPatchRequest {
    return this.data as ProjectAgentPatchRequest;
  }
}
