// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

import type { ObjectReference, ListMeta } from './base';

export type ProjectSettings = ObjectReference & {
  group_access: string;
  project_id: string;
  repositories: string;
};

export type ProjectSettingsList = ListMeta & {
  items: ProjectSettings[];
};

export type ProjectSettingsCreateRequest = {
  group_access?: string;
  project_id: string;
  repositories?: string;
};

export type ProjectSettingsPatchRequest = {
  group_access?: string;
  project_id?: string;
  repositories?: string;
};

export class ProjectSettingsBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  build(): ProjectSettingsCreateRequest {
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    return this.data as ProjectSettingsCreateRequest;
  }
}

export class ProjectSettingsPatchBuilder {
  private data: Record<string, unknown> = {};


  groupAccess(value: string): this {
    this.data['group_access'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  repositories(value: string): this {
    this.data['repositories'] = value;
    return this;
  }

  build(): ProjectSettingsPatchRequest {
    return this.data as ProjectSettingsPatchRequest;
  }
}
