// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { ProjectDocument, ProjectDocumentList, ProjectDocumentCreateRequest, ProjectDocumentPatchRequest } from './project_document';

export class ProjectDocumentAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: ProjectDocumentCreateRequest, opts?: RequestOptions): Promise<ProjectDocument> {
    return ambientFetch<ProjectDocument>(this.config, 'POST', '/project_documents', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<ProjectDocument> {
    return ambientFetch<ProjectDocument>(this.config, 'GET', `/project_documents/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<ProjectDocumentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<ProjectDocumentList>(this.config, 'GET', `/project_documents${qs}`, undefined, opts);
  }
  async update(id: string, patch: ProjectDocumentPatchRequest, opts?: RequestOptions): Promise<ProjectDocument> {
    return ambientFetch<ProjectDocument>(this.config, 'PATCH', `/project_documents/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<ProjectDocument> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
