// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { ObjectReference, ListMeta } from './base';

export type Role = ObjectReference & {
  built_in: boolean;
  description: string;
  display_name: string;
  name: string;
  permissions: string;
};

export type RoleList = ListMeta & {
  items: Role[];
};

export type RoleCreateRequest = {
  built_in?: boolean;
  description?: string;
  display_name?: string;
  name: string;
  permissions?: string;
};

export type RolePatchRequest = {
  built_in?: boolean;
  description?: string;
  display_name?: string;
  name?: string;
  permissions?: string;
};

export class RoleBuilder {
  private data: Record<string, unknown> = {};


  builtIn(value: boolean): this {
    this.data['built_in'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  permissions(value: string): this {
    this.data['permissions'] = value;
    return this;
  }

  build(): RoleCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as RoleCreateRequest;
  }
}

export class RolePatchBuilder {
  private data: Record<string, unknown> = {};


  builtIn(value: boolean): this {
    this.data['built_in'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  displayName(value: string): this {
    this.data['display_name'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  permissions(value: string): this {
    this.data['permissions'] = value;
    return this;
  }

  build(): RolePatchRequest {
    return this.data as RolePatchRequest;
  }
}

