// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 6aa380e2811c748da7e24b50bed0ae9908aed8cd7f7760fe274776b84726faf2
// Generated: 2026-04-21T16:19:04Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { SessionMessage, SessionMessageList, SessionMessageCreateRequest } from './session_message';

export class SessionMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    return '/sessions/{id}/messages'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: SessionMessageCreateRequest, opts?: RequestOptions): Promise<SessionMessage> {
    return ambientFetch<SessionMessage>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<SessionMessage> {
    return ambientFetch<SessionMessage>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionMessageList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<SessionMessage> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
