// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { SessionMessage, SessionMessageList } from './session_message';

export class SessionMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async list(sessionId: string, listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionMessageList>(this.config, 'GET', `/sessions/${sessionId}/messages${qs}`, undefined, opts);
  }

  async *listAll(sessionId: string, size: number = 100, opts?: RequestOptions): AsyncGenerator<SessionMessage> {
    let page = 1;
    while (true) {
      const result = await this.list(sessionId, { page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
