// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { SessionCheckIn, SessionCheckInList, SessionCheckInCreateRequest, SessionCheckInPatchRequest } from './session_check_in';

export class SessionCheckInAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: SessionCheckInCreateRequest, opts?: RequestOptions): Promise<SessionCheckIn> {
    return ambientFetch<SessionCheckIn>(this.config, 'POST', '/session_check_ins', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<SessionCheckIn> {
    return ambientFetch<SessionCheckIn>(this.config, 'GET', `/session_check_ins/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionCheckInList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionCheckInList>(this.config, 'GET', `/session_check_ins${qs}`, undefined, opts);
  }
  async update(id: string, patch: SessionCheckInPatchRequest, opts?: RequestOptions): Promise<SessionCheckIn> {
    return ambientFetch<SessionCheckIn>(this.config, 'PATCH', `/session_check_ins/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<SessionCheckIn> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
