// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 6aa380e2811c748da7e24b50bed0ae9908aed8cd7f7760fe274776b84726faf2
// Generated: 2026-04-24T08:29:20Z

import type { ObjectReference, ListMeta } from './base';

export type SessionMessage = ObjectReference & {
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionMessageList = ListMeta & {
  items: SessionMessage[];
};

export type SessionMessageCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionMessagePatchRequest = {
};

export class SessionMessageBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionMessageCreateRequest {
    return this.data as SessionMessageCreateRequest;
  }
}

export class SessionMessagePatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionMessagePatchRequest {
    return this.data as SessionMessagePatchRequest;
  }
}
