// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 47119590c5b99c8ae2cf4280c6cd43829ffd283a58c334f22ff8aedc01851068
// Generated: 2026-02-26T15:57:52Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Session, SessionList, SessionCreateRequest, SessionPatchRequest, SessionStatusPatchRequest } from './session';

export class SessionAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: SessionCreateRequest, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'POST', '/sessions', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'GET', `/sessions/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<SessionList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<SessionList>(this.config, 'GET', `/sessions${qs}`, undefined, opts);
  }
  async update(id: string, patch: SessionPatchRequest, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'PATCH', `/sessions/${id}`, patch, opts);
  }

  async updateStatus(id: string, patch: SessionStatusPatchRequest, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'PATCH', `/sessions/${id}/status`, patch, opts);
  }

  async start(id: string, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'POST', `/sessions/${id}/start`, undefined, opts);
  }

  async stop(id: string, opts?: RequestOptions): Promise<Session> {
    return ambientFetch<Session>(this.config, 'POST', `/sessions/${id}/stop`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Session> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
