// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

import type { ObjectReference, ListMeta } from './base';

export type SessionCheckIn = ObjectReference & {
  agent_id: string;
  branch: string;
  next_steps: string;
  phase: string;
  pr: string;
  session_id: string;
  summary: string;
  test_count: number;
  worktree: string;
};

export type SessionCheckInList = ListMeta & {
  items: SessionCheckIn[];
};

export type SessionCheckInCreateRequest = {
  agent_id: string;
  branch?: string;
  next_steps?: string;
  phase?: string;
  pr?: string;
  session_id: string;
  summary?: string;
  test_count?: number;
  worktree?: string;
};

export type SessionCheckInPatchRequest = {
  agent_id?: string;
  branch?: string;
  next_steps?: string;
  phase?: string;
  pr?: string;
  session_id?: string;
  summary?: string;
  test_count?: number;
  worktree?: string;
};

export class SessionCheckInBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  branch(value: string): this {
    this.data['branch'] = value;
    return this;
  }

  nextSteps(value: string): this {
    this.data['next_steps'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  pr(value: string): this {
    this.data['pr'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  summary(value: string): this {
    this.data['summary'] = value;
    return this;
  }

  testCount(value: number): this {
    this.data['test_count'] = value;
    return this;
  }

  worktree(value: string): this {
    this.data['worktree'] = value;
    return this;
  }

  build(): SessionCheckInCreateRequest {
    if (!this.data['agent_id']) {
      throw new Error('agent_id is required');
    }
    if (!this.data['session_id']) {
      throw new Error('session_id is required');
    }
    return this.data as SessionCheckInCreateRequest;
  }
}

export class SessionCheckInPatchBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  branch(value: string): this {
    this.data['branch'] = value;
    return this;
  }

  nextSteps(value: string): this {
    this.data['next_steps'] = value;
    return this;
  }

  phase(value: string): this {
    this.data['phase'] = value;
    return this;
  }

  pr(value: string): this {
    this.data['pr'] = value;
    return this;
  }

  sessionId(value: string): this {
    this.data['session_id'] = value;
    return this;
  }

  summary(value: string): this {
    this.data['summary'] = value;
    return this;
  }

  testCount(value: number): this {
    this.data['test_count'] = value;
    return this;
  }

  worktree(value: string): this {
    this.data['worktree'] = value;
    return this;
  }

  build(): SessionCheckInPatchRequest {
    return this.data as SessionCheckInPatchRequest;
  }
}

