// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { User, UserList, UserCreateRequest, UserPatchRequest } from './user';

export class UserAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: UserCreateRequest, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'POST', '/users', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'GET', `/users/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<UserList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<UserList>(this.config, 'GET', `/users${qs}`, undefined, opts);
  }
  async update(id: string, patch: UserPatchRequest, opts?: RequestOptions): Promise<User> {
    return ambientFetch<User>(this.config, 'PATCH', `/users/${id}`, patch, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<User> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
