// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

import type { ObjectReference, ListMeta } from './base';

export type User = ObjectReference & {
  email: string;
  name: string;
  username: string;
};

export type UserList = ListMeta & {
  items: User[];
};

export type UserCreateRequest = {
  email?: string;
  name: string;
  username: string;
};

export type UserPatchRequest = {
  email?: string;
  name?: string;
  username?: string;
};

export class UserBuilder {
  private data: Record<string, unknown> = {};


  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['username']) {
      throw new Error('username is required');
    }
    return this.data as UserCreateRequest;
  }
}

export class UserPatchBuilder {
  private data: Record<string, unknown> = {};


  email(value: string): this {
    this.data['email'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  username(value: string): this {
    this.data['username'] = value;
    return this;
  }

  build(): UserPatchRequest {
    return this.data as UserPatchRequest;
  }
}
