---
apiVersion: v1
kind: Template
metadata:
  name: ambient-api-server-secrets
  annotations:
    description: Ambient API Server Secrets
parameters:

- name: DATABASE_HOST
  description: Hostname for the database server.

- name: DATABASE_PORT
  description: Port of the database server.

- name: DATABASE_NAME
  description: Name for the database in the server.

- name: DATABASE_USER
  description: User for the database server.

- name: DATABASE_PASSWORD
  description: Password for the database user.

- name: SENTRY_KEY
  description: Private key used in Sentry DSN

objects:

- apiVersion: v1
  kind: Secret
  metadata:
    name: ambient-api-server-rds
  stringData:
    db.host: ${DATABASE_HOST}
    db.port: ${DATABASE_PORT}
    db.name: ${DATABASE_NAME}
    db.user: ${DATABASE_USER}
    db.password: ${DATABASE_PASSWORD}

- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: authentication
  data:
    jwks.json: |-
      {
        "keys": []
      }

    acl.yml: |-
      - claim: email
        pattern: ^.*@redhat\.com$
