// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type AGUIEventAPI struct {
	client *Client
}

func (c *Client) AGUIEvents() *AGUIEventAPI {
	return &AGUIEventAPI{client: c}
}

func (a *AGUIEventAPI) Create(ctx context.Context, resource *types.AGUIEvent) (*types.AGUIEvent, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal a_g_u_i_event: %w", err)
	}
	var result types.AGUIEvent
	if err := a.client.do(ctx, http.MethodPost, "/ag_ui_events", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AGUIEventAPI) Get(ctx context.Context, id string) (*types.AGUIEvent, error) {
	var result types.AGUIEvent
	if err := a.client.do(ctx, http.MethodGet, "/ag_ui_events/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AGUIEventAPI) List(ctx context.Context, opts *types.ListOptions) (*types.AGUIEventList, error) {
	var result types.AGUIEventList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/ag_ui_events", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *AGUIEventAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.AGUIEvent, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.AGUIEvent
	if err := a.client.do(ctx, http.MethodPatch, "/ag_ui_events/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AGUIEventAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.AGUIEvent] {
	return NewIterator(func(page int) (*types.AGUIEventList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
