// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type AgentAPI struct {
	client *Client
}

func (c *Client) Agents() *AgentAPI {
	return &AgentAPI{client: c}
}

func (a *AgentAPI) Create(ctx context.Context, resource *types.Agent) (*types.Agent, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal agent: %w", err)
	}
	var result types.Agent
	if err := a.client.do(ctx, http.MethodPost, "/agents", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentAPI) Get(ctx context.Context, id string) (*types.Agent, error) {
	var result types.Agent
	if err := a.client.do(ctx, http.MethodGet, "/agents/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentAPI) List(ctx context.Context, opts *types.ListOptions) (*types.AgentList, error) {
	var result types.AgentList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/agents", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *AgentAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Agent, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Agent
	if err := a.client.do(ctx, http.MethodPatch, "/agents/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Agent] {
	return NewIterator(func(page int) (*types.AgentList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
