// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9fc1cbdb0aa1a90c2d918eacbe4ed297f7ab6a3916b473be1bd5b82344f28f4d
// Generated: 2026-03-12T10:28:42Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type AgentMessageAPI struct {
	client *Client
}

func (c *Client) AgentMessages() *AgentMessageAPI {
	return &AgentMessageAPI{client: c}
}

func (a *AgentMessageAPI) Create(ctx context.Context, resource *types.AgentMessage) (*types.AgentMessage, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal agent_message: %w", err)
	}
	var result types.AgentMessage
	if err := a.client.do(ctx, http.MethodPost, "/agent_messages", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentMessageAPI) Get(ctx context.Context, id string) (*types.AgentMessage, error) {
	var result types.AgentMessage
	if err := a.client.do(ctx, http.MethodGet, "/agent_messages/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentMessageAPI) List(ctx context.Context, opts *types.ListOptions) (*types.AgentMessageList, error) {
	var result types.AgentMessageList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/agent_messages", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *AgentMessageAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.AgentMessage, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.AgentMessage
	if err := a.client.do(ctx, http.MethodPatch, "/agent_messages/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *AgentMessageAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.AgentMessage] {
	return NewIterator(func(page int) (*types.AgentMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
