// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

package client

import (
	"context"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type InboxMessageAPI struct {
	client *Client
}

func (c *Client) InboxMessages() *InboxMessageAPI {
	return &InboxMessageAPI{client: c}
}

func (a *InboxMessageAPI) List(ctx context.Context, projectID, paID string, opts *types.ListOptions) (*types.InboxMessageList, error) {
	var result types.InboxMessageList
	path := "/projects/" + url.PathEscape(projectID) + "/agents/" + url.PathEscape(paID) + "/inbox"
	if err := a.client.doWithQuery(ctx, http.MethodGet, path, nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *InboxMessageAPI) ListAll(ctx context.Context, projectID, paID string, opts *types.ListOptions) *Iterator[types.InboxMessage] {
	return NewIterator(func(page int) (*types.InboxMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, projectID, paID, &o)
	})
}

func (a *InboxMessageAPI) Delete(ctx context.Context, projectID, paID, msgID string) error {
	path := "/projects/" + url.PathEscape(projectID) + "/agents/" + url.PathEscape(paID) + "/inbox/" + url.PathEscape(msgID)
	return a.client.do(ctx, http.MethodDelete, path, nil, http.StatusNoContent, nil)
}
