// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: f0ec84178602f3437cc365a1e354b5286dbd72ff5c138db499664f62b927bb61
// Generated: 2026-02-28T15:30:52Z

package client

type Listable[T any] interface {
	GetItems() []T
	GetTotal() int
	GetPage() int
	GetSize() int
}

type Iterator[T any] struct {
	fetchPage func(page int) (Listable[T], error)
	items     []T
	index     int
	page      int
	total     int
	done      bool
	err       error
}

func NewIterator[T any, L Listable[T]](fetchPage func(page int) (L, error)) *Iterator[T] {
	return &Iterator[T]{
		fetchPage: func(page int) (Listable[T], error) {
			return fetchPage(page)
		},
		page:  0,
		index: -1,
	}
}

func (it *Iterator[T]) Next() bool {
	if it.done || it.err != nil {
		return false
	}
	it.index++
	if it.index < len(it.items) {
		return true
	}
	it.page++
	result, err := it.fetchPage(it.page)
	if err != nil {
		it.err = err
		return false
	}
	it.items = result.GetItems()
	it.index = 0
	it.total = result.GetTotal()
	if len(it.items) == 0 {
		it.done = true
		return false
	}
	return true
}

func (it *Iterator[T]) Item() T {
	return it.items[it.index]
}

func (it *Iterator[T]) Err() error {
	return it.err
}
