// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: aa4fadb1f795265128f058fdc5ffa2bd25396c8516537ea97ba3671dc007b8fc
// Generated: 2026-06-11T02:31:17Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectAPI struct {
	client *Client
}

func (c *Client) Projects() *ProjectAPI {
	return &ProjectAPI{client: c}
}

func (a *ProjectAPI) Create(ctx context.Context, resource *types.Project) (*types.Project, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project: %w", err)
	}
	var result types.Project
	if err := a.client.do(ctx, http.MethodPost, "/projects", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAPI) Get(ctx context.Context, id string) (*types.Project, error) {
	var result types.Project
	if err := a.client.do(ctx, http.MethodGet, "/projects/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectList, error) {
	var result types.ProjectList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/projects", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Project, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Project
	if err := a.client.do(ctx, http.MethodPatch, "/projects/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/projects/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ProjectAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Project] {
	return NewIterator(func(page int) (*types.ProjectList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
