// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectAgentAPI struct {
	client *Client
}

func (c *Client) ProjectAgents() *ProjectAgentAPI {
	return &ProjectAgentAPI{client: c}
}

func (a *ProjectAgentAPI) Create(ctx context.Context, resource *types.ProjectAgent) (*types.ProjectAgent, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_agent: %w", err)
	}
	var result types.ProjectAgent
	if err := a.client.do(ctx, http.MethodPost, "/projects", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) Get(ctx context.Context, id string) (*types.ProjectAgent, error) {
	var result types.ProjectAgent
	if err := a.client.do(ctx, http.MethodGet, "/projects/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectAgentList, error) {
	var result types.ProjectAgentList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/projects", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectAgentAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ProjectAgent] {
	return NewIterator(func(page int) (*types.ProjectAgentList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
