// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectDocumentAPI struct {
	client *Client
}

func (c *Client) ProjectDocuments() *ProjectDocumentAPI {
	return &ProjectDocumentAPI{client: c}
}

func (a *ProjectDocumentAPI) Create(ctx context.Context, resource *types.ProjectDocument) (*types.ProjectDocument, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_document: %w", err)
	}
	var result types.ProjectDocument
	if err := a.client.do(ctx, http.MethodPost, "/project_documents", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectDocumentAPI) Get(ctx context.Context, id string) (*types.ProjectDocument, error) {
	var result types.ProjectDocument
	if err := a.client.do(ctx, http.MethodGet, "/project_documents/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectDocumentAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProjectDocumentList, error) {
	var result types.ProjectDocumentList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/project_documents", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProjectDocumentAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ProjectDocument, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ProjectDocument
	if err := a.client.do(ctx, http.MethodPatch, "/project_documents/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectDocumentAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ProjectDocument] {
	return NewIterator(func(page int) (*types.ProjectDocumentList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
