// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 9a8e623edcfae33acf56edf974d1859a127c22915d4831cb786daba2b398ca37
// Generated: 2026-03-21T21:30:53Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProjectAgentAPI struct {
	client *Client
}

func (c *Client) ProjectAgents() *ProjectAgentAPI {
	return &ProjectAgentAPI{client: c}
}

func (a *ProjectAgentAPI) Create(ctx context.Context, projectID string, resource *types.ProjectAgent) (*types.ProjectAgent, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal project_agent: %w", err)
	}
	var result types.ProjectAgent
	path := "/projects/" + url.PathEscape(projectID) + "/agents"
	if err := a.client.do(ctx, http.MethodPost, path, body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) Get(ctx context.Context, projectID, paID string) (*types.ProjectAgent, error) {
	var result types.ProjectAgent
	path := "/projects/" + url.PathEscape(projectID) + "/agents/" + url.PathEscape(paID)
	if err := a.client.do(ctx, http.MethodGet, path, nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) List(ctx context.Context, projectID string, opts *types.ListOptions) (*types.ProjectAgentList, error) {
	var result types.ProjectAgentList
	path := "/projects/" + url.PathEscape(projectID) + "/agents"
	if err := a.client.doWithQuery(ctx, http.MethodGet, path, nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) ListAll(ctx context.Context, projectID string, opts *types.ListOptions) *Iterator[types.ProjectAgent] {
	return NewIterator(func(page int) (*types.ProjectAgentList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, projectID, &o)
	})
}

func (a *ProjectAgentAPI) Update(ctx context.Context, projectID, paID string, patch map[string]any) (*types.ProjectAgent, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ProjectAgent
	path := "/projects/" + url.PathEscape(projectID) + "/agents/" + url.PathEscape(paID)
	if err := a.client.do(ctx, http.MethodPatch, path, body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProjectAgentAPI) Delete(ctx context.Context, projectID, paID string) error {
	path := "/projects/" + url.PathEscape(projectID) + "/agents/" + url.PathEscape(paID)
	return a.client.do(ctx, http.MethodDelete, path, nil, http.StatusNoContent, nil)
}
