// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: aa4fadb1f795265128f058fdc5ffa2bd25396c8516537ea97ba3671dc007b8fc
// Generated: 2026-06-11T02:31:17Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type RoleAPI struct {
	client *Client
}

func (c *Client) Roles() *RoleAPI {
	return &RoleAPI{client: c}
}

func (a *RoleAPI) Create(ctx context.Context, resource *types.Role) (*types.Role, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal role: %w", err)
	}
	var result types.Role
	if err := a.client.do(ctx, http.MethodPost, "/roles", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) Get(ctx context.Context, id string) (*types.Role, error) {
	var result types.Role
	if err := a.client.do(ctx, http.MethodGet, "/roles/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) List(ctx context.Context, opts *types.ListOptions) (*types.RoleList, error) {
	var result types.RoleList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/roles", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *RoleAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Role, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Role
	if err := a.client.do(ctx, http.MethodPatch, "/roles/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *RoleAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/roles/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *RoleAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Role] {
	return NewIterator(func(page int) (*types.RoleList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
