// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 1f13484383a70932b3935d2a673097e06e067aba46dfbb9ebe2b330ef1155cce
// Generated: 2026-03-10T14:18:34Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionCheckInAPI struct {
	client *Client
}

func (c *Client) SessionCheckIns() *SessionCheckInAPI {
	return &SessionCheckInAPI{client: c}
}

func (a *SessionCheckInAPI) Create(ctx context.Context, resource *types.SessionCheckIn) (*types.SessionCheckIn, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session_check_in: %w", err)
	}
	var result types.SessionCheckIn
	if err := a.client.do(ctx, http.MethodPost, "/session_check_ins", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionCheckInAPI) Get(ctx context.Context, id string) (*types.SessionCheckIn, error) {
	var result types.SessionCheckIn
	if err := a.client.do(ctx, http.MethodGet, "/session_check_ins/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionCheckInAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionCheckInList, error) {
	var result types.SessionCheckInList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/session_check_ins", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionCheckInAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.SessionCheckIn, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.SessionCheckIn
	if err := a.client.do(ctx, http.MethodPatch, "/session_check_ins/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionCheckInAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.SessionCheckIn] {
	return NewIterator(func(page int) (*types.SessionCheckInList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
