// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 404b5671af96841f4a876b6192afc6358b4fb8e082ca2b6da499efcf3f72c781
// Generated: 2026-03-20T16:48:23Z
// NOTE: Paths hand-corrected post-generation — generator cannot infer nested routes.

package client

import (
	"context"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionMessageAPI struct {
	client *Client
}

func (c *Client) SessionMessages() *SessionMessageAPI {
	return &SessionMessageAPI{client: c}
}

func (a *SessionMessageAPI) List(ctx context.Context, sessionID string, opts *types.ListOptions) (*types.SessionMessageList, error) {
	var result types.SessionMessageList
	path := "/sessions/" + url.PathEscape(sessionID) + "/messages"
	if err := a.client.doWithQuery(ctx, http.MethodGet, path, nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionMessageAPI) ListAll(ctx context.Context, sessionID string, opts *types.ListOptions) *Iterator[types.SessionMessage] {
	return NewIterator(func(page int) (*types.SessionMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, sessionID, &o)
	})
}
